### ISSUE TITLE
How to use imu to correct the map

### ISSUE THREAD

**Issue by jianzilai** [cartographer-project/cartographer_ros#1005]
I have used rplidar to generate the map, but if the rplidar is not placed horizontally, the generated map will have errors, so I want to use imu to correct, how to use imu into the cartographer

**Comment by gaschler** [comment]
Edit the urdf file and set the lidar to imu transform.
A small technical limitation is that tracking frame needs to be at the same position as the IMU origin, so the translation between IMU and lidar has to go into the tracking--lidar transform, not into the tracking--IMU transform.
