### ISSUE TITLE
Problems to configure 

### ISSUE THREAD

**Issue by MrGitGo** [cartographer-project/cartographer_ros#1008]
I have installed google cartographer and I'm trying to build a tf for my sensor. But I don't know how to do it in the correct way. My rqt looks like this if I start backpack_3d.launch:

![bildschirmfoto vom 2018-09-11 11-30-07](https://user-images.githubusercontent.com/33628476/45351744-2b9aad80-b5b7-11e8-934e-86a738e12d43.png)

I wrote the base_link like in the tutorial for tf. And I mentioned my problem in a issue before that I don't know how to link it to my camera

This is my backpack_3d.lua:

```
options = {
  map_builder = MAP_BUILDER,
  trajectory_builder = TRAJECTORY_BUILDER,
  map_frame = "map",
  tracking_frame = "base_link",
  published_frame = "base_link",
  odom_frame = "odom",
  provide_odom_frame = true,
  publish_frame_projected_to_2d = false,
  use_odometry = false,
  use_nav_sat = false,
  use_landmarks = false,

  num_laser_scans = 0,
  num_multi_echo_laser_scans = 0,
  num_subdivisions_per_laser_scan = 1,
  num_point_clouds = 2,
  lookup_transform_timeout_sec = 0.2,
  submap_publish_period_sec = 0.3,
  pose_publish_period_sec = 5e-3,
  trajectory_publish_period_sec = 30e-3,
  rangefinder_sampling_ratio = 1.,
  odometry_sampling_ratio = 1.,
  fixed_frame_pose_sampling_ratio = 1.,
  imu_sampling_ratio = 1.,
  landmarks_sampling_ratio = 1.,
}
TRAJECTORY_BUILDER_3D.num_accumulated_range_data = 160
MAP_BUILDER.use_trajectory_builder_3d = true
MAP_BUILDER.num_background_threads = 7
POSE_GRAPH.optimization_problem.huber_scale = 5e2
POSE_GRAPH.optimize_every_n_nodes = 320
POSE_GRAPH.constraint_builder.sampling_ratio = 0.03
POSE_GRAPH.optimization_problem.ceres_solver_options.max_num_iterations = 10
POSE_GRAPH.constraint_builder.min_score = 0.62
POSE_GRAPH.constraint_builder.global_localization_min_score = 0.66
return options 

```

And this is the rviz view I don't know why I have an error in the submaps:
![bildschirmfoto vom 2018-09-11 12-11-00](https://user-images.githubusercontent.com/33628476/45353873-67844180-b5bc-11e8-81e4-d3633aaf95b8.png)

I have changed the topic of PointCloud2 to /scan_matched_points2 but I don't get the sensor data 

This is how my camera.launch looks like I did a remap there but it's not working properly i guess:
![bildschirmfoto vom 2018-09-11 13-45-08](https://user-images.githubusercontent.com/33628476/45358234-0e6eda80-b5c9-11e8-97d5-dc336326230f.png)

**Comment by Semih67** [comment]
So instead of linking the camera with the base, I have to link the laser data of the camera?

**Comment by MichaelGrupp** [comment]
Closing as answered / inactive.
