### ISSUE TITLE
z position drifting error

### ISSUE THREAD

**Issue by Howonjung** [cartographer-project/cartographer_ros#1029]
Hello, 

I am currently testing  cartographer package to make a outdoor map and I found that there is large z

position drifting as time goes on. even thought there are some bumps on the road, I believe cartographer 

itself can deal with this issue. so I don't know what is reason of this z position drifting problem. 

any comments would be appreciated.

[lua.file](https://drive.google.com/drive/folders/1c7iHICa1c76IG6iO9LAYle8KE1td5A0p?usp=sharing)
[urdf.file](https://drive.google.com/file/d/1jTld11VfoJsX4JFWnGKHN6Ce5AFjukGA/view?usp=sharing)
[launch.file](https://drive.google.com/drive/folders/1kk_6WR__2wQDIT4xrTcf0-LZ3HtGZKJA?usp=sharing)
[bag.file](https://drive.google.com/file/d/15_MMCEfX3z9NsQC-ZOe6S7_Ay_mqL0YM/view?usp=sharing)

![top_view](https://user-images.githubusercontent.com/33755943/46129052-6ca9e780-c270-11e8-83c2-b28830741f98.png)
![sideview downhill_road](https://user-images.githubusercontent.com/33755943/46129071-7c293080-c270-11e8-9bcd-460f482bc89a.png)

![side_view plain_road](https://user-images.githubusercontent.com/33755943/46129072-7cc1c700-c270-11e8-9b45-bc424656a9a8.png)

**Comment by gaschler** [comment]
The most common reason is that your IMU to lidar transform is wrong by that drift angle.
Please calibrate your extrinsic IMU orientation, see https://github.com/googlecartographer/cartographer/issues/1199#issuecomment-398080355
