### ISSUE TITLE
How to set the new trajectory

### ISSUE THREAD

**Issue by carl1218** [cartographer-project/cartographer_ros#1033]
Hi:
I am running 2d slam online,when i call  rosservice call /finish_trajectory 0 ,than set a new trajectory,
i call : 
` rosrun cartographer_ros cartographer_start_trajectory -configuration_basename=backpack_2d.lua -configuration_directory=/home/calyu/catkin_ws/install_isolated/share/cartographer_ros/configuration_files -initial_pose="{to_trajectory_id=0,relative_pose={translation={0.0,0.0,10},rotation={0.,0.,0.0}}}`

I set the Z-axis to 10m，I wan to drafting the map in this plane.
At first, i can see the cloud points in this plane(Z-axis = 10m).but when start to  drawing the map , the Z axis will change to the initial position.(Z-axis = 0m).
How can i to set the new trajectory in the new plane (Z-axis ≠ 0)

this is cloud points picture:
![6v 3e8d 0 2 _e 4z79ao](https://user-images.githubusercontent.com/17962046/46194649-a2b09f80-c334-11e8-9096-bfb4cedb31b1.png)

**Comment by alfred31** [comment]
From my point of view two possible reasons:
1) It maybe caused due to the loop closure of cartographer, the algorithm detects your position in the map, that is Z=0 and then it corrects the base_link pose within the map
2) Since it is a 2D problem cartographer might not allow Z axis different from 0

Regards

**Comment by carl1218** [comment]
@alfred31 
Thank you for your reply.Is there any way to change  it?
Now,i can drafting the map in this plane(Z-axis ≠ 0),but
when i runned :rosservice call /finish_trajectory 0 want to save this map ,the Z axis will change to the initial position.look like this:
![46901358-9277f300-cee4-11e8-8183-071a3478b729](https://user-images.githubusercontent.com/17962046/47765515-4828ab80-dd05-11e8-8dac-09c99ad8108f.png)
Than runned finish trajectory:
![46901373-fdc1c500-cee4-11e8-85bc-6c93651ea3cc](https://user-images.githubusercontent.com/17962046/47765533-62628980-dd05-11e8-89b8-0b93c496f2f1.png)

**Comment by MichaelGrupp** [comment]
This is not really a supported use case of 2D SLAM.
