### ISSUE TITLE
How to enable landmark option at pr2 simluator

### ISSUE THREAD

**Issue by EvanYehh** [cartographer-project/cartographer_ros#1046]
Hi
We try to enable landmark option at pr2 environment, but it failed.
After we enable the use_landmarks option in pr2.lua, the error log is the same as issue#909
And we try to publish a fake landmark data, but it still suffer the same issue. "Queue waiting for data: (0, landmark)"

We had some questions
1. What will generate the landmark data for topic /landmark? the sensor(does it need some specific sensor or just common lidar/camera ?) or the sensor-data need to be processed and transformed then output as landmark data?
2. How to generate the /landmark_pose_list? Since we provide a fake landmark data but there is no /landmark_pose_list output
3. Is there a document for landmark, about how to setup environment or verification? 

The pr2 environment and publish command as below
Install pr2 and gazebo related package and launch a pr2 world
roslaunch pr2_gazebo pr2_wg_world.launch

Launch cartographer to create a map
roslaunch cartographer_ros demo_pr2.launch
(enable landmark option and remove bag file config in demo_pr2.launch)

Generate a fake landmark data
rostopic pub -r 10 /landmark cartographer_ros_msgs/LandmarkList ' { header: { frame_id: "map" }, landmark :[ { id: "0", tracking_from_landmark_transform : { position: { x: 0.0, y: 0, z: 0 }, orientation: { x: 0, y: 0, z: 0, w: 0 } }, translation_weight : 0.0, rotation_weight : 0.0 } ] } '

Thanks

**Comment by mojovski** [comment]
I am also about to try to use the landmark feature in cartographer. So I dont actually have a solution, but your command to publish a fake landmark should be
```
rostopic pub /landmark cartographer_ros_msgs/LandmarkList ' { header: { frame_id: "map" }, landmarks :[ { id: "0", tracking_from_landmark_transform : { position: { x: 1.0, y: 0, z: 0 }, orientation: { x: 0, y: 0, z: 0, w: 0 } }, translation_weight : 0.0, rotation_weight : 0.0 } ] } '
```
(landmarks instead of landmark)

**Comment by MichaelGrupp** [comment]
See linked issue.
