### ISSUE TITLE
failing to build cartographer due to protobuf library conflicts.

### ISSUE THREAD

**Issue by fgrigis** [cartographer-project/cartographer_ros#1047]
I'm trying to build cartographer_ros under Ubuntu 16.04 / Ros Kinetic using catkin build. 

![screenshot from 2018-10-04 10-45-09](https://user-images.githubusercontent.com/17498133/46464234-2c91ba00-c7c6-11e8-9512-4df073168122.png)

(the lines above Cmake Error reading my_lib_protodsgdsag/usr/local/lib and
include_directory can be ignored, I have them printed out for debuging reasons)

See the attached picture of the error message I get. From what I found on so far, Ubuntu 16.04 comes with Protobuf version 2.6.1 but cartographer needs at least 3.0.0. I updated to 3.6.1 (successfully I believe) but now there seems to be an issue with the libraries. 

How can i resolve this issue? I tried to create simlinks from the old library files at /usr/lib/x86_64-linux-gnu to the location where the updating of protobuf put the corresponding lib files for protobuf 3.6.1, which is at /usr/local/lib. But this couldn't resolve the issue either.

**Comment by Tutorgaming** [comment]
Did you try building cartographer_ros using the _old CLI_ "catkin_make_isolated" ? 

Reference from this GIST [https://gist.github.com/kdaun/51b7d19bbcd5e0798c8415cd093078fb](https://gist.github.com/kdaun/51b7d19bbcd5e0798c8415cd093078fb)

and this topic [#625](https://github.com/googlecartographer/cartographer_ros/issues/625)

which make the cartographer_ros use the isolated protobuf 3.4.1 (which is not going to effect the as-is system protobuf 2.6 that you're currently on)
