### ISSUE TITLE
How to set the new trajectory in different plane ?

### ISSUE THREAD

**Issue by carl1218** [cartographer-project/cartographer_ros#1060]
Hi,
  I am running 2d slam online ,when i call rosservice call /finish_trajectory,and set the new trajectory to z-axis=5,i runned:
`rosrun cartographer_ros cartographer_start_trajectory -configuration_basename=backpack_2d.lua -configuration_directory=/home/calyu/catkin_ws/install_isolated/share/cartographer_ros/configuration_files -initial_pose="{to_trajectory_id=0,relative_pose={translation={0.0,0.0,5},rotation={0.,0.,0.0}}}`
i can see the map look like this:
![4cpcumov9kx j0a 5 d94](https://user-images.githubusercontent.com/17962046/46901358-9277f300-cee4-11e8-8183-071a3478b729.png)

i want to save this map ,so than i runned rosservice call /finish_trajectory 1,but the Z axis will change to the initial position.(Z-axis = 0m).
look like this:
![0g j_4 4_nxr4g g agz4](https://user-images.githubusercontent.com/17962046/46901373-fdc1c500-cee4-11e8-85bc-6c93651ea3cc.png)

How can i to set the new trajectory in the new plane (Z-axis ≠ 0) and save this map?

**Comment by MichaelGrupp** [comment]
2D mode doesn't support multiple planes.
