### ISSUE TITLE
roslaunch error

### ISSUE THREAD

**Issue by ghost** [cartographer-project/cartographer_ros#1061]
I followed the build manual in https://google-cartographer-ros.readthedocs.io/en/latest/.

When running demos -> roslaunch cartographer_ros demo_backpack_2d.launch bag_filename:=${HOME}/Downloads/cartographer_paper_deutsches_museum.bag

got an error like below:

> ~/Downloads$ roslaunch cartographer_ros demo_backpack_2d.launch bag_filename:=${HOME}/Downloads/cartographer_paper_deutsches_museum.bag
> ... logging to /home/sangwon/.ros/log/8d259dda-cf57-11e8-9960-74e5f90b4176/roslaunch-DESKTOP-06ER8PJ-4462.log
> Checking log directory for disk usage. This may take awhile.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://DESKTOP-06ER8PJ:59557/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /robot_description: <...>
>  * /rosdistro: kinetic
>  * /rosversion: 1.12.14
>  * /use_sim_time: True
> 
> NODES
>   /
>     cartographer_node (cartographer_ros/cartographer_node)
>     cartographer_occupancy_grid_node (cartographer_ros/cartographer_occupancy_grid_node)
>     playbag (rosbag/play)
>     robot_state_publisher (robot_state_publisher/robot_state_publisher)
>     rviz (rviz/rviz)
> 
> ROS_MASTER_URI=http://localhost:11311
> 
> process[robot_state_publisher-1]: started with pid [4485]
> process[cartographer_node-2]: started with pid [4486]
> process[cartographer_occupancy_grid_node-3]: started with pid [4487]
> process[rviz-4]: started with pid [4518]
> process[playbag-5]: started with pid [4534]
> [ INFO] [1539484182.995822900]: I1014 11:29:42.000000  4486 configuration_file_resolver.cc:41] Found '/home/sangwon/catkin_ws/install_isolated/share/cartographer_ros/configuration_files/backpack_2d.lua' for 'backpack_2d.lua'.
> [ INFO] [1539484182.997693600]: I1014 11:29:42.000000  4486 configuration_file_resolver.cc:41] Found '/home/sangwon/catkin_ws/install_isolated/share/cartographer/configuration_files/map_builder.lua' for 'map_builder.lua'.
> [ INFO] [1539484182.998520700]: I1014 11:29:42.000000  4486 configuration_file_resolver.cc:41] Found '/home/sangwon/catkin_ws/install_isolated/share/cartographer/configuration_files/map_builder.lua' for 'map_builder.lua'.
> [ INFO] [1539484182.999387900]: I1014 11:29:42.000000  4486 configuration_file_resolver.cc:41] Found '/home/sangwon/catkin_ws/install_isolated/share/cartographer/configuration_files/pose_graph.lua' for 'pose_graph.lua'.
> [ INFO] [1539484182.999816100]: I1014 11:29:42.000000  4486 configuration_file_resolver.cc:41] Found '/home/sangwon/catkin_ws/install_isolated/share/cartographer/configuration_files/pose_graph.lua' for 'pose_graph.lua'.
> [ INFO] [1539484183.000881800]: I1014 11:29:43.000000  4486 configuration_file_resolver.cc:41] Found '/home/sangwon/catkin_ws/install_isolated/share/cartographer/configuration_files/trajectory_builder.lua' for 'trajectory_builder.lua'.
> [ INFO] [1539484183.001341900]: I1014 11:29:43.000000  4486 configuration_file_resolver.cc:41] Found '/home/sangwon/catkin_ws/install_isolated/share/cartographer/configuration_files/trajectory_builder.lua' for 'trajectory_builder.lua'.
> [ INFO] [1539484183.002238800]: I1014 11:29:43.000000  4486 configuration_file_resolver.cc:41] Found '/home/sangwon/catkin_ws/install_isolated/share/cartographer/configuration_files/trajectory_builder_2d.lua' for 'trajectory_builder_2d.lua'.
> [ INFO] [1539484183.002806900]: I1014 11:29:43.000000  4486 configuration_file_resolver.cc:41] Found '/home/sangwon/catkin_ws/install_isolated/share/cartographer/configuration_files/trajectory_builder_2d.lua' for 'trajectory_builder_2d.lua'.
> [ INFO] [1539484183.004019500]: I1014 11:29:43.000000  4486 configuration_file_resolver.cc:41] Found '/home/sangwon/catkin_ws/install_isolated/share/cartographer/configuration_files/trajectory_builder_3d.lua' for 'trajectory_builder_3d.lua'.
> [ INFO] [1539484183.004599400]: I1014 11:29:43.000000  4486 configuration_file_resolver.cc:41] Found '/home/sangwon/catkin_ws/install_isolated/share/cartographer/configuration_files/trajectory_builder_3d.lua' for 'trajectory_builder_3d.lua'.
> F1014 11:29:43.007673  4576 thread_pool.cc:85] Check failed: nice(10) != -1 (-1 vs. -1) 
> [FATAL] [1539484183.022102500]: F1014 11:29:43.000000  4576 thread_pool.cc:85] Check failed: nice(10) != -1 (-1 vs. -1) 
> F1014 11:29:43.007820  4577 thread_pool.cc:85] Check failed: nice(10) != -1 (-1 vs. -1) F1014 11:29:43.008060  4578 thread_pool.cc:85] Check failed: nice(10) != -1 (-1 vs. -1) F1014 11:29:43.008222  4579 thread_pool.cc:85] Check failed: nice(10) != -1 (-1 vs. -1) 
> [FATAL] [1539484183.025009500]: F1014 11:29:43.000000  4577 thread_pool.cc:85] Check failed: nice(10) != -1 (-1 vs. -1) 
> F1014 11:29:43.007820  4577 thread_pool.cc:85] Check failed: nice(10) != -1 (-1 vs. -1) F1014 11:29:43.008060  4578 thread_pool.cc:85] Check failed: nice(10) != -1 (-1 vs. -1) F1014 11:29:43.008222  4579 thread_pool.cc:85] Check failed: nice(10) != -1 (-1 vs. -1) 
> [FATAL] [1539484183.025580600]: F1014 11:29:43.000000  4578 thread_pool.cc:85] Check failed: nice(10) != -1 (-1 vs. -1) 
> F1014 11:29:43.007820  4577 thread_pool.cc:85] Check failed: nice(10) != -1 (-1 vs. -1) F1014 11:29:43.008060  4578 thread_pool.cc:85] Check failed: nice(10) != -1 (-1 vs. -1) F1014 11:29:43.008222  4579 thread_pool.cc:85] Check failed: nice(10) != -1 (-1 vs. -1) 
> [FATAL] [1539484183.026028300]: F1014 11:29:43.000000  4579 thread_pool.cc:85] Check failed: nice(10) != -1 (-1 vs. -1) 
> [ INFO] [1539484183.056879400]: I1014 11:29:43.000000  4486 submap_2d.cc:187] Added submap 1
> failed to get the current screen resources
> *** Check failure stack trace: ***
> *** Check failure stack trace: ***
> *** Check failure stack trace: ***
> *** Check failure stack trace: ***
>     @     0x7f8c5c7db5cd  google::LogMessage::Fail()
>     @     0x7f8c5c7db5cd  google::LogMessage::Fail()
>     @     0x7f8c5c7db5cd  google::LogMessage::Fail()
>     @     0x7f8c5c7db5cd  google::LogMessage::Fail()
>     @     0x7f8c5c7dd433  google::LogMessage::SendToLog()
>     @     0x7f8c5c7dd433  google::LogMessage::SendToLog()
>     @     0x7f8c5c7dd433  google::LogMessage::SendToLog()
>     @     0x7f8c5c7dd433  google::LogMessage::SendToLog()
> [ INFO] [1539484184.060239300, 1432647016.482676000]: I1014 11:29:44.000000  4486 map_builder_bridge.cc:130] Added trajectory with ID '0'.
>     @     0x7f8c5c7db15b  google::LogMessage::Flush()
>     @     0x7f8c5c7db15b  google::LogMessage::Flush()
>     @     0x7f8c5c7db15b  google::LogMessage::Flush()
>     @     0x7f8c5c7db15b  google::LogMessage::Flush()
>     @     0x7f8c5c7dde1e  google::LogMessageFatal::~LogMessageFatal()
>     @     0x7f8c5c7dde1e  google::LogMessageFatal::~LogMessageFatal()
>     @     0x7f8c5c7dde1e  google::LogMessageFatal::~LogMessageFatal()
>     @     0x7f8c5c7dde1e  google::LogMessageFatal::~LogMessageFatal()
>     @           0x64f2f4  cartographer::common::ThreadPool::DoWork()
>     @           0x64f2f4  cartographer::common::ThreadPool::DoWork()
>     @           0x64f2f4  cartographer::common::ThreadPool::DoWork()
>     @           0x64f2f4  cartographer::common::ThreadPool::DoWork()
>     @     0x7f8c593f8c80  (unknown)
>     @     0x7f8c593f8c80  (unknown)
>     @     0x7f8c593f8c80  (unknown)
>     @     0x7f8c593f8c80  (unknown)
>     @     0x7f8c5c3876ba  start_thread
>     @     0x7f8c5c3876ba  start_thread
>     @     0x7f8c5c3876ba  start_thread
>     @     0x7f8c5c3876ba  start_thread
>     @     0x7f8c58b4741d  clone
>     @     0x7f8c58b4741d  clone
>     @     0x7f8c58b4741d  clone
>     @     0x7f8c58b4741d  clone
>     @              (nil)  (unknown)
> QXcbConnection: XCB error: 170 (Unknown), sequence: 163, resource id: 90, major code: 146 (Unknown), minor code: 20
> [cartographer_node-2] process has died [pid 4486, exit code -6, cmd /home/sangwon/catkin_ws/install_isolated/lib/cartographer_ros/cartographer_node -configuration_directory /home/sangwon/catkin_ws/install_isolated/share/cartographer_ros/configuration_files -configuration_basename backpack_2d.lua echoes:=horizontal_laser_2d __name:=cartographer_node __log:=/home/sangwon/.ros/log/8d259dda-cf57-11e8-9960-74e5f90b4176/cartographer_node-2.log].
> log file: /home/sangwon/.ros/log/8d259dda-cf57-11e8-9960-74e5f90b4176/cartographer_node-2*.log
> ================================================================================REQUIRED process [rviz-4] has died!
> process has finished cleanly
> log file: /home/sangwon/.ros/log/8d259dda-cf57-11e8-9960-74e5f90b4176/rviz-4*.log
> Initiating shutdown!
> ================================================================================
> [playbag-5] killing on exit
> [rviz-4] killing on exit
> [cartographer_occupancy_grid_node-3] killing on exit
> [robot_state_publisher-1] killing on exit
> shutting down processing monitor...
> ... shutting down processing monitor complete
> done
> 

what problem is in there?? 

I used windows subsytem for linux (wsl), ubuntu 16.04.

**Comment by MichaelGrupp** [comment]
Please put your console output in a code block, nobody can read this.
https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks

> I used windows subsytem for linux (wsl), ubuntu 16.04.

Does it work in a native Ubuntu environment?
