### ISSUE TITLE
cartographer can't save map

### ISSUE THREAD

**Issue by haolingyi** [cartographer-project/cartographer_ros#1070]
I success install cartographer in Ubuntu 16.04.
ans use Rpliadr-A2 and turtlebot2 to set map.
now I can see map in rviz but when i want to save map by command
rosrun map_server map_saver my_map
Terminal always show "Waiting for the map"
I can't get map files

**Comment by zhenliysu** [comment]
First, you should check whether  the "map" topic has been published？ 
The "map" topic is published by cartographer_occupancy_grid_node node.
e.g.
  <node name="cartographer_occupancy_grid_node" pkg="cartographer_ros"
      type="cartographer_occupancy_grid_node" args="-resolution 0.05" />

**Comment by haolingyi** [comment]
Thank you,I have solved this problem by set cartographer_occupancy_grid_node.

**Comment by zhaoyu24** [comment]
> Thank you,I have solved this problem by set cartographer_occupancy_grid_node.

I had the same problem,could please tell me how do you set the cartographer_occupancy_grid_node.

**Comment by MichaelGrupp** [comment]
> > Thank you,I have solved this problem by set cartographer_occupancy_grid_node.
> 
> I had the same problem,could please tell me how do you set the cartographer_occupancy_grid_node.

You can rosrun cartographer_ros cartographer_occupancy_grid_node ...
