### ISSUE TITLE
Build fails if ros-kinetic-abseil-cpp is installed

### ISSUE THREAD

**Issue by ojura** [cartographer-project/cartographer_ros#1075]
For some reason, the outdated ROS Abseil is preferred over the in-tree one. This is on Ubuntu Xenial. Sorry for the sparse report, this should be enough to reproduce :)

**Comment by ojura** [comment]
Removing ros-kinetic-abseil-cpp fixes the build. Here's a log of the build errors: https://gist.github.com/ojura/8b8a5102e7c07e4eb4d0ebc93c1d80ac

**Comment by MichaelGrupp** [comment]
This is mentioned in the docs now.
