### ISSUE TITLE
/submap_query

### ISSUE THREAD

**Issue by woshidaye** [cartographer-project/cartographer_ros#1079]
I use services “/submap_query” to get data from submaps, data is one-dimensional, how to convert one-dimensional data into two-dimensional map matrix?
Through this service, I can save a cells as well as height and width. But the product of height and width is not equal to the number of elements in the cells.How to convert one-dimensional data into two-dimensional map matrix?

**Comment by MichaelGrupp** [comment]
I recommend to check in the source code how this data is assembled.
