### ISSUE TITLE
TurtleBot odom frame transform to map frame is unstable

### ISSUE THREAD

**Issue by rdesc** [cartographer-project/cartographer_ros#1090]
Hi,

I have been trying to debug an issue while running **cartographer on a local computer** with a **TurtleBot 2 + kobuki base + rplidar** and would like some input (carto and nav stack do not run on same device). The odom frame (published frame) with respect to the map frame is unstable when driving **especially while turning** and eventually SLAM gets all wacky. I am not sure if the issue lies with the navigation stack on the robot itself and its a matter of increasing publishing rate somewhere or some parameter in the cartographer lua file needs to be tuned.

1. output of rosbag validate: https://gist.githubusercontent.com/rdesc/c150c520cdc29fd0dbee29aa011fcc01/raw/243e28eeb8dbd4757db5c23cc710525eeb8134fc/cartographer_rosbag_validate_output_2018-11-05-14-41-16.txt 
**Note:** 
          - the flat_world_imu_node was running while recording which takes in imu_in (did a remap from /mobile_base/sensors/imu_data_raw to imu_in)
          - frame_id gyro_link is sent on three topics: /mobile_base/sensors/imu_data, imu_in, and imu_out not sure if this is an issue (default with TB2 is two /mobile_base/sensors/imu_data and /mobile_base/sensors/imu_data_raw)
 
2. link to cartographer_ros branch: https://github.com/icclab/cartographer_ros and link to turtlebot2 branch: https://github.com/icclab/icclab_turtlebot/tree/turtlebot2
            - slam launch file: https://github.com/icclab/cartographer_ros/blob/master/cartographer_ros/launch/turtlebot2_slam.launch
            - lua file: https://github.com/icclab/cartographer_ros/blob/master/cartographer_ros/configuration_files/turtlebot2_slam.lua
            - tb2 urdf: https://github.com/icclab/icclab_turtlebot/blob/turtlebot2/robots/turtlebot.urdf.xacro
            - launch file used for bringup: https://github.com/icclab/icclab_turtlebot/blob/turtlebot2/launch/minimal_exploration.launch
**Note:** TB2 nav stacks params are essentially default right now

3. bag_file: https://drive.google.com/file/d/1i3viSINY4pW1Jj5UM2TmLWQp3PAtwW4e/view?usp=sharing

**Other comments:**
- this issue is especially troublesome when doing SLAM for a long period of time or doing pure localization
- unrelated to this issue and less of a priority the global costmap does not get updated properly 

Thanks for the help.

**Update 1:**
I have made the following changes in my lua file 
````````````````````````
published_frame = "base_footprint",
provide_odom_frame = true,
use_pose_extrapolator = true,
use_odometry = false,
``````````````````````````
So now cartographer provides the odom frame not the TB2 and it is much more stable though the actual mapping is less accurate... Therefore I would still like to use my original configuration (using odom from TB2) though still unsure how to tune it properly. 

**Update 2:**
I may have solved the problem by doing the following:
- lowered max translational and rotational velocities and accelerations in Nav stack for Turtlebot
- modified original lua file to use pose extrapolator changes can be found here https://github.com/icclab/cartographer_ros/commit/35c44821396aa68248822aaac281dffe371351b4

**Comment by MichaelGrupp** [comment]
We can't invest time unfortunately to help you here, but it looks like your updates are going into the right direction :+1:
