### ISSUE TITLE
Clarification needed for odom -> base_link transform

### ISSUE THREAD

**Issue by rdesc** [cartographer-project/cartographer_ros#1095]
Hi,

So I have been doing a lot of browsing through the docs and discussions here on github and need a once and for all clarification on the "odom -> base_link" transform.

This was the explanation given by @gaschler https://github.com/googlecartographer/cartographer_ros/issues/1056#issuecomment-437291442  
>Cartographer (and other SLAM algorithms) output two transforms, "map -> odom" for the global loop closure correction and "odom -> base_link" for the transform from current pose of the robot to the first one.

This is all makes sense to me up until a component with odometry is invovled, what happens then? 
>A common configuration is to receive messages from the odometry/ topic in a frame_id "base_footprint" or similar, and define the (static) transform "base_link <-> base_footprint" in urdf.

I am using cartographer with a TurtleBot and this confuses me because by default below is the configuration for the component that provides odometry and by default it does the transform "odom -> base_footprint" which conflicts with cartographer (two components publishing same transform).
``````````````````````
# Name of the odometry TF frame (string, default: odom)
odom_frame: odom

# Name of the base TF frame  (string, default: base_footprint)
base_frame: base_footprint
````````````````````````
Furthermore in the cartographer_turtlebot repo the provided demo has the following tf_tree
![image](https://user-images.githubusercontent.com/39059473/48266325-54141c00-e42f-11e8-92dc-09b9677ef061.png)

The transform "odom" -> "base_footprint" in this demo is not done by carto but by playbag which originally would've been by mobile_base (same component described above that provides odometry). Also compared to the other demos which do not include an odometry component the "odom" frame here is very jittery and jumps from one place to another. 

So my question is what should the complete configuration look like when an odometry component is included assuming that cartographer should **always** be doing two transforms "map -> odom" and "odom -> base_link" (or equivalent).

Appreciate the help.

**Comment by tianb03** [comment]
Odometry is the estimation of the motion blindly, in Robotics we always call it dead reckoning. 

So this part can be published by your mobile robot itself, like mobile_base for turtlebot. Odometry is given by wheel encoder. In such case you should disable cartographer to broadcast odom->base_link, or else there is a conflict.

If you fly a drone, and also you want to have an estimated odometry (I think this ), then cartographer should publish odom->base_link which is calculated based on range sensors and probably IMU.
