### ISSUE TITLE
Outdoor mapping Loop not close

### ISSUE THREAD

**Issue by qs371102** [cartographer-project/cartographer_ros#1110]
Hello

I'm using cartographer for outdoor mapping.I use Visual Odometry (topic: /zed/odom), IMU (topic: /imu/data)  .Laser only used the front 180 degree.

final map image 
[https://drive.google.com/file/d/1ikTg0s1kHxhTAFN4OwTb1QMRqkZZRM5g/view?usp=sharing](url)
output from rosbag_validate
[https://gist.github.com/qs371102/11e203283657d34a27c96d9fa6bbe97f](url)
bag file
[https://drive.google.com/file/d/1-TayPX_BSlbwcygIMkishmwGdXB7oZoP/view?usp=sharing](url)
cartographer_ros
[https://github.com/qs371102/cartographer_ros](url)

The launch file is demo_andi.launch

gampping result show that the Visual Odometry is reliable

![map](https://user-images.githubusercontent.com/9305008/49218161-a92dc700-f40a-11e8-8327-7ffcba91dbd8.png)

After the bagfile play finished cant see any tend to loop close.I try to Tuning the params but work little .Any advice would be appreciated.

**Comment by MichaelGrupp** [comment]
I would recommend to increase the search window of the fast correlative scan matcher in the config.
