### ISSUE TITLE
Using cartographer in a non-centralized multi robot system

### ISSUE THREAD

**Issue by MPihlap** [cartographer-project/cartographer_ros#1113]
Greetings!

As I understand it, Cartographer works with multiple trajectories under a single central cartographer node, which listens to the appropriate scan topics for each trajectory and constructs submaps and trajectories based on the input data.

Would it be possible to decentralize the system by running a separate Cartographer node on each of the robots and establishing communications between them (with the SubmapQuery service) to share submaps? Would I also need to provide information about the trajectories themselves or can Cartographer stitch the maps together based on the submaps alone?

Thank you in advance,
Meelis

**Comment by MichaelGrupp** [comment]
See linked issue.
