### ISSUE TITLE
Help required with tuning global SLAM loop closure in 2D

### ISSUE THREAD

**Issue by frederikscholz** [cartographer-project/cartographer_ros#1119]
Hello,

after getting satisfactory results with my local SLAM, I am now having a little bit of trouble with achieving proper loop closure when procuring a larger map.
I'd be grateful for any pointers towards which values seem off and should be tuned.

- the [rosbag_validate](https://gist.github.com/frederikscholz/7920fe75e3ad00a05f8319d0673941ab) for the bag in question

- the [branch](https://github.com/frederikscholz/Pepper-Navigation) with the configuration files 

- the [bag](https://drive.google.com/open?id=12fZXMoSLq7SADWdk5bRhN8eKbdPlaCfI) 

[Solved partially, thanks @ojura] Also, whenever I save the occupancy_grid as a map, it is somehow mirrored and the obstacles don't show up in the resulting .pgm file, does anyone know what could cause this issue, or how I could mirror the .yaml file?
[edit] Saving the map from the pbstream fixed the obstacles not showing up, but unfortunately the map is still mirrored

Thanks,
Frederik

**Comment by rdesc** [comment]
> frame_id "base_link" is send on multiple topics. It was seen at least on /scan and /naoqi_driver_node/imu/torso

This needs to be fixed. Your imu sensor should have its own frame id coming down from the base_link.

> Time delta histogram for consecutive messages on topic "/scan" (frame_id: "base_link")

Ideally same with your scan sensor. I'll leave it to others to comment on your .lua file.

**Comment by frederikscholz** [comment]
> > frame_id "base_link" is send on multiple topics. It was seen at least on /scan and /naoqi_driver_node/imu/torso
> 
> This needs to be fixed. Your imu sensor should have its own frame id coming down from the base_link.
> 
> > Time delta histogram for consecutive messages on topic "/scan" (frame_id: "base_link")
> 
> Ideally same with your scan sensor. I'll leave it to others to comment on your .lua file.

I'll look into that, thank you!

> Whats the command you use to save the occupancy grid map?

rosrun map_server map_saver -f <mapname>

**Comment by ojura** [comment]
Instead of using the map saver, I would recomend saving the Cartographer state into a .pbstream and using Cartographer's own pbstream_to_ros_map tool.

Map_saver does agressive thresholding and messes up the walls in Cartographer's maps, IIRC.

**Comment by frederikscholz** [comment]
It worked, thank you! I'd been stuck on that for a while now.

**Comment by ojura** [comment]
The map being mirrored sounds your tracking frame-> laser frame transform is wrong. Maybe your lidar data should be interpreted as in your lidar was mounted upside down? In any case, sounds like a problem with your data.
