### ISSUE TITLE
Unable to load map from file

### ISSUE THREAD

**Issue by CycleMark** [cartographer-project/cartographer_ros#1131]
Hi,

I know I had this working at one point. I've saved a pb file and a bag file but I cannot get cartographer to load either and rebuild the map.

1) I've tried the following commands:

roslaunch cartographer_turtlebot turtlebot_urg_lidar_2d.launch configuration_basename:=turtlebot_urg_lidar_2d.lua load_state_filename:=${HOME}//cartographer_v1.0/cartographer_full_downstairs_20102018.bag.pbstream

and including the original bag file (Which I'm not sure why I'd want/need to reply all the data again)

roslaunch cartographer_turtlebot turtlebot_urg_lidar_2d.launch configuration_basename:=turtlebot_urg_lidar_2d.lua load_state_filename:=${HOME}//cartographer_v1.0/cartographer_full_downstairs_20102018.bag.pbstream bag_filename:=${HOME}//cartographer_v1.0/cartographer_full_downstairs_20102018.bag

And re-read:
https://google-cartographer-ros.readthedocs.io/en/latest/assets_writer.html

Do I really need to load the bag file every time? It sems pointless as that is effectively replying all the data.

Thanks and Regards

Mark

**Comment by MichaelGrupp** [comment]
> Do I really need to load the bag file every time?

No, this is not required.
