### ISSUE TITLE
cartographer_ros laserscan error

### ISSUE THREAD

**Issue by ytgcljj** [cartographer-project/cartographer_ros#1134]
![_20181220182314](https://user-images.githubusercontent.com/27713475/50279331-5c2a9700-0484-11e9-8790-70d8e3465066.jpg)
help me thanks

**Comment by koki-ogura** [comment]
ydlidar?

**Comment by ytgcljj** [comment]
@koki-ogura  what

**Comment by koki-ogura** [comment]
If LiDAR you are using is ydlidar, there is a problem with scan message generation, failing to translate tf causes such a problem.

**Comment by ytgcljj** [comment]
i use hokuyo  UTM-30LX
