### ISSUE TITLE
The frequency of Tf topic published is unstable and decreased

### ISSUE THREAD

**Issue by zldodo** [cartographer-project/cartographer_ros#1137]
Hello,

I've working with Cartographer 2D for mapping and localization. When I ran the demo bag file(cartographer_paper_deutsches_museum.bag) for mapping, I found the frequency of tf published was unstable and decreasing/
![demo_tf_1](https://user-images.githubusercontent.com/26668433/50384106-e0864f80-06fa-11e9-8b4f-d4c611819007.png)
![demo_tf_3](https://user-images.githubusercontent.com/26668433/50384107-e1b77c80-06fa-11e9-862c-5bd2bf5f7f24.png)

This situation behaved worse with my bag( using Velodyne64 without IMU).
This situation is normal ?OR  it depends on hardware or something else? I have no idea that where the frequency of TF  is set.
In addition, for localization, if IMU was not available, would Cartographer work well? Do you have some test results about the localization accuracy in this case? 

Look forward for your help! Thank you!

**Comment by gaschler** [comment]
No, by default, Cartographer ROS should publish at a fixed rate (even if it is waiting for input).

Are you sure you are measuring only Cartographer's own output and not including other tf messages, for instance those that may be inside a bag file you play?

**Comment by zldodo** [comment]
I'm sure that there is no tf messages inside bags.  The case of decreasing rates was not found when using Offline_node.  As  you said, it is published at a fixed rate. 

Could you tell where the fixed rate is set？ in .lua file? pose_publish_period_sec = 5e-3

**Comment by gaschler** [comment]
Correct, pose_publish_period_sec.
