### ISSUE TITLE
Follow official docs got nothing result

### ISSUE THREAD

**Issue by jinfagang** [cartographer-project/cartographer_ros#1142]
I have build cartographer and try generate a 3D point cloud map from provided rosbag, I am downloaded this one ` cartographer_paper_deutsches_museum.bag`, 

And I start with:

```
roslaunch cartographer_ros demo_backpack_3d.launch  bag_filename:=`pwd`/cartographer_paper_deutsches_museum.bag

```

the rviz windows just show nothing......

![image](https://user-images.githubusercontent.com/21303438/50500583-5a1c9580-0a8d-11e9-8121-c17ee06b282f.png)

Does anyone know what's going on here? How should I bringup the on-line 3D mapping process?

And how to eventually generate a .ply file which I needs for 3d pointcloud map?

**Comment by gaschler** [comment]
You could post the warning from the terminal.
The screenshot is inconclusive.
