### ISSUE TITLE
Is it possible to build 3D map by PR2 using the tilting laser

### ISSUE THREAD

**Issue by tongtybj** [cartographer-project/cartographer_ros#1150]
I am thinking to try building 3D map by PR2, by using base_hokuyo_laser, tilting_laser, wheel odometry.
Has anyone tried this combination ?

**Comment by MichaelGrupp** [comment]
If its not possible, how can I track the changes so I know that (x1,y1) needs to be updated on (x2,y2) after a loop closure?
