### ISSUE TITLE
caartographer release 1.0 and ros wapper 1.0 does not compile well

### ISSUE THREAD

**Issue by jinfagang** [cartographer-project/cartographer_ros#1155]
Master branch fails, just checkout both 1.0, got this erro:

```
/usr/local/include/cartographer/io/points_processor_pipeline_builder.h:23:42: fatal error: absl/container/flat_hash_map.h: No such file or directory
 #include "absl/container/flat_hash_map.h"

/usr/local/include/cartographer/mapping/id.h:30:32: fatal error: absl/memory/memory.h: No such file or directory

```

It's all about this `absl` package.................. any fix on this issue?

**Comment by gaschler** [comment]
Are you linking to Cartographer (ROS)?
Then, you need to also find its dependencies:

```
find_package(cartographer REQUIRED)
include("${CARTOGRAPHER_CMAKE_DIR}/functions.cmake")
```

as done in https://github.com/googlecartographer/cartographer_ros/blob/master/cartographer_ros/CMakeLists.txt#L49

Are you compiling Cartographer ROS yourself? Then, you should in addition choose the master version, where absl is included with `external_project_add`.

**Comment by MichaelGrupp** [comment]
I'm trying to fix the build instructions for the latest revisions, see #1531.
