### ISSUE TITLE
Cmake Error with cartographer_rviz

### ISSUE THREAD

**Issue by MirrorSaver** [cartographer-project/cartographer_ros#1163]
On Ubuntu 16.04 I build the cartographer toolchain. However I encounter the following dependency problem in the cartographer_rviz package.  I use the command catkin build but its the same with catkin_make_isolated

```
/devel/share/cartographer_ros/cmake/cartographer_rosConfig.cmake:148 (message):
  Project 'cartographer_rviz' tried to find library '-lpthread'.  The library
  is neither a target nor built/installed properly.  Did you compile project
  'cartographer_ros'? Did you find_package() it before the subdirectory
  containing its code is included?
Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  CMakeLists.txt:39 (find_package)

```

**Comment by ojura** [comment]
https://github.com/larics/cartographer_superbuild/issues/2#issuecomment-452604811

**Comment by KerryShao** [comment]
> [larics/cartographer_superbuild#2 (comment)](https://github.com/larics/cartographer_superbuild/issues/2#issuecomment-452604811)

3X, This fixs my building error.

**Comment by foreverlms** [comment]
> > [larics/cartographer_superbuild#2 (comment)](https://github.com/larics/cartographer_superbuild/issues/2#issuecomment-452604811)
> 
> 3X, This fixs my building error.

Hi, how did you fix this error? I am doing build just in command line. No Clion, just the command `catkin_make_isolated --install --use-ninja`
