### ISSUE TITLE
Request for ROS2 branch. Already depolyed cartograher_ros on turtlebot, ros2 crystal.

### ISSUE THREAD

**Issue by ahuizxc** [cartographer-project/cartographer_ros#1172]
Hi all
I have been successfully depolyed cartographer_ros on both turtlebot2 and turtlebot3, based on https://github.com/ROBOTIS-GIT/cartographer.
Thereby, I request for ros2 branch to share my code :).
Thanks a lot!

**Comment by MichaelGrupp** [comment]
See here for a new discussion on ROS2: https://github.com/cartographer-project/cartographer_ros/issues/1536

Closing this one.
