### ISSUE TITLE
use point cloud as input

### ISSUE THREAD

**Issue by songyuxiang** [cartographer-project/cartographer_ros#1177]
Hello,

I have a point cloud generated by a trajectory of GPS and IMU(with error). Do you know if it's possible to adjust the point cloud by cartographer_ros? If yes, how to use point cloud as input?

Thanks

**Comment by Semih67** [comment]
You have to do a remap. In your launch file, in the <cartographer_node> write this:
<remap from="points2" to="NAME OF YOUR PC TOPIC"/>
But you have to change the parameter num_point_clouds in your lua. Depending on how many point clouds you have, if you have just one you have to do the remap like it's in the example, but if you have two change it to "points2_1" "points2_2"
