### ISSUE TITLE
How can I get a 3D pointcloud map?

### ISSUE THREAD

**Issue by MrGitGo** [cartographer-project/cartographer_ros#1185]
According to the tutorial, I called `roslaunch cartographer _ros assets_writer.launch bag_filenames:= ... pose_graph_filenames:=...`

And I get the error: ```
terminate called after throwing an instance of 'tf2::ExtrapolationException'

what(): lookup would require extrapolation into the past. Requested time ... but the earliest data is at time ..., when looking up transform from frame [map] to frame [imu]
```

**Comment by MichaelGrupp** [comment]
We can't help you from the data provided. You need to debug this.
