### ISSUE TITLE
The class required for this display, 'Submaps', could not be loaded.

### ISSUE THREAD

**Issue by herogan2017** [cartographer-project/cartographer_ros#1205]
when I run cartographer 2D demo in my computer, found following error:

Submaps
The class required for this display, 'Submaps', could not be loaded.
Error:
According to the loaded plugin descriptions the class Submaps with base class type rviz::Display does not exist. Declared types are rviz/Axes rviz/Camera rviz/DepthCloud rviz/Effort rviz/FluidPressure rviz/Grid rviz/GridCells rviz/Illuminance rviz/Image rviz/InteractiveMarkers rviz/LaserScan rviz/Map rviz/Marker rviz/MarkerArray rviz/Odometry rviz/Path rviz/PointCloud rviz/PointCloud2 rviz/PointStamped rviz/Polygon rviz/Pose rviz/PoseArray rviz/PoseWithCovariance rviz/Range rviz/RelativeHumidity rviz/RobotModel rviz/TF rviz/Temperature rviz/WrenchStamped

**Comment by MichaelGrupp** [comment]
`cartographer_rviz` needs to be correctly installed and your ROS environment needs to be installed correctly so it can load it when it's installed.
