### ISSUE TITLE
ROS Configuration Issues for multiple sensors.

### ISSUE THREAD

**Issue by asb9594** [cartographer-project/cartographer_ros#1213]
Hello,

We are a group working on an autonomous driving golf cart at RIT and are currently trying to test our bag file with Cartographer and have had no success. We get an error in RVIZ shown below,

Fixed Frame
No tf data. Actual error: Fixed Frame [map] does not exist.

We are using /tf and have configure the .lua file to what we believed to be correct but haven't been able to get Cartographer to run using our .bag file. We have ran through the demos provided by Cartographer and have been studying the Cartographer documentation but haven't been able to resolve the issue. Below are links to a Git repository and an image of the tf view frames. We believe that the error is caused by our system having a loam_gps node in between map and odom but haven't been able to adjust things properly to resolve the issue. 

The system uses a Velodyne Puck (16 channel) and single channel velodyne along with a monocular camera. 

Thank you for your assistance.

Below is a zip file containing the .lua file, and two launch files,
[lua.zip](https://github.com/googlecartographer/cartographer_ros/files/2916347/lua.zip)

The bag file is located here:
https://drive.google.com/file/d/13IlYQUuf5hX2iJoB6IUzbK5iNJdSDTgw/view?usp=sharing

tf frames:
![img_0970](https://user-images.githubusercontent.com/46330782/53586742-cc295d80-3b56-11e9-8ab3-9c8c14cd928a.jpg)

**Comment by MichaelGrupp** [comment]
I can't help with your custom setup, but I would recommend to start with a very simple configuration without this Loam frame and then gradually add more complexity to find out what causes issues.
