### ISSUE TITLE
Loop closure demo

### ISSUE THREAD

**Issue by TuskAW** [cartographer-project/cartographer_ros#1226]
Hello Everybody. I have been running the demo examples, and after running the localization demo, I don't see in rviz any graphical indication that loop closures were found. Am I misunderstanding the meaning of the pose markers on the map? I was expecting to see markers with the (1,x) label to match markers with the (0,x) label from the mapping run as indications of loop closures. Thanks.

**Comment by MichaelGrupp** [comment]
Loop closure constraints are shown as yellow lines if you enabled the marker display for "inter constraints".

> I was expecting to see markers with the (1,x) label to match markers with the (0,x) label from the mapping run as indications of loop closures

If you mean the submap pose markers: they don't need to match when there's a successful loop closure. Especially if you use a different dataset and settings for localization.
