### ISSUE TITLE
Alternative 3D mapping

### ISSUE THREAD

**Issue by MrGitGo** [cartographer-project/cartographer_ros#1233]
Is there an alternative for the assets writer? I want to use the cartographer and get 3D maps live, not with a bag file.I am able to use the assets writer, but it's not satisfactory. I tried to increase the decay time of the point cloud, but the solution is not that good. I have looked a little bit around and found this link: https://www.youtube.com/watch?v=Ve9kWX_KXus

Is there an algorithm that I can use to get this? Or is there any plug in or tool?   

I hope you can help me with this

**Comment by MichaelGrupp** [comment]
Closing as inactive.
