### ISSUE TITLE
odometry laserScan calibration

### ISSUE THREAD

**Issue by ZhengPan2014** [cartographer-project/cartographer_ros#1247]
**Question:** I want to know is that important to calibrate the base_link to laser frame accurately so that  I can use the odometry data for 2d mapping?

**Done:** I have tried my best to install laser scan sensor in the center of my turtlebot,  but unfortunately with a small transform T which was measured roughly by hand. The final map sticked below was messing and overlapping , even worse than mapping with only laserScan data. 
![image](https://user-images.githubusercontent.com/15884732/55208283-a60be180-5218-11e9-8db5-38b3e6729d38.png)

this is the tf tree:
![image](https://user-images.githubusercontent.com/15884732/55208389-16b2fe00-5219-11e9-929b-7b1436811194.png)

this is the ros backpack_2d/lua:
![image](https://user-images.githubusercontent.com/15884732/55208499-672a5b80-5219-11e9-9b5c-17438ea37848.png)
and this is the ros launch file:
![image](https://user-images.githubusercontent.com/15884732/55208557-8de89200-5219-11e9-8d24-a46d95aa43b2.png)
 
the **odom_tf_node** will read in /odom topic from bag and send tf  of odom->base_footprint.
**Help:** anyone can give me some advice? appreciate for any references, thanks!
@esteve @SirVer @damienrg @damonkohler @skohlbr

**Comment by Mafuqiang** [comment]
can you show me your urdf file with odometry? When I run cartographer with odometry, I get some error. Thank you very much.

**Comment by Fanny-one** [comment]
Have you solve the issue? I have met the same problem.

**Comment by MichaelGrupp** [comment]
We can't help with this calibration, but you need to make sure the scanner is level and the offset is correct. You could also check your odometry quality since you use it.

**Comment by Alcatrazee** [comment]
you can actully use the lidar to do the mapping without the odometry, and tune the cartographer parameters, a well tuned cartographer slam is better than the one with a bad odometry, just a suggestion
