### ISSUE TITLE
 catkin_make_isolated error

### ISSUE THREAD

**Issue by ytgcljj** [cartographer-project/cartographer_ros#1248]
[ 67%] Linking CXX executable cartographer.mapping.internal.constraints.constraint_builder_3d_test
[ 67%] Linking CXX executable cartographer.mapping.internal.constraints.constraint_builder_2d_test
libcartographer.a(constraint_builder_3d.cc.o)：在函数‘cartographer::mapping::constraints::ConstraintBuilder3D::ComputeConstraint(cartographer::mapping::SubmapId const&, cartographer::mapping::NodeId const&, bool, cartographer::mapping::TrajectoryNode::Data const*, cartographer::transform::Rigid3<double> const&, cartographer::transform::Rigid3<double> const&, cartographer::mapping::constraints::ConstraintBuilder3D::SubmapScanMatcher const&, std::unique_ptr<cartographer::mapping::PoseGraphInterface::Constraint, std::default_delete<cartographer::mapping::PoseGraphInterface::Constraint> >*)’中：
constraint_builder_3d.cc:(.text+0x12e0)：对‘ceres::Solver::Summary::Summary()’未定义的引用
libcartographer.a(ceres_scan_matcher_2d.cc.o)：在函数‘cartographer::mapping::scan_matching::CeresScanMatcher2D::Match(Eigen::Matrix<double, 2, 1, 0, 2, 1> const&, cartographer::transform::Rigid2<double> const&, std::vector<cartographer::sensor::RangefinderPoint, std::allocator<cartographer::sensor::RangefinderPoint> > const&, cartographer::mapping::Grid2D const&, cartographer::transform::Rigid2<double>*, ceres::Solver::Summary*) const’中：
ceres_scan_matcher_2d.cc:(.text+0x17a)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*)’未定义的引用
ceres_scan_matcher_2d.cc:(.text+0x245)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*)’未定义的引用
ceres_scan_matcher_2d.cc:(.text+0x30b)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*)’未定义的引用
libcartographer.a(ceres_scan_matcher_3d.cc.o)：在函数‘cartographer::mapping::scan_matching::CeresScanMatcher3D::Match(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, cartographer::transform::Rigid3<double> const&, std::vector<std::pair<std::vector<cartographer::sensor::RangefinderPoint, std::allocator<cartographer::sensor::RangefinderPoint> > const*, cartographer::mapping::HybridGrid const*>, std::allocator<std::pair<std::vector<cartographer::sensor::RangefinderPoint, std::allocator<cartographer::sensor::RangefinderPoint> > const*, cartographer::mapping::HybridGrid const*> > > const&, cartographer::transform::Rigid3<double>*, ceres::Solver::Summary*)’中：
ceres_scan_matcher_3d.cc:(.text+0x3b7)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*, double*)’未定义的引用
ceres_scan_matcher_3d.cc:(.text+0x5f4)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*)’未定义的引用
ceres_scan_matcher_3d.cc:(.text+0x6f7)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*)’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/cartographer.mapping.internal.constraints.constraint_builder_3d_test.dir/build.make:160: recipe for target 'cartographer.mapping.internal.constraints.constraint_builder_3d_test' failed
make[2]: *** [cartographer.mapping.internal.constraints.constraint_builder_3d_test] Error 1
CMakeFiles/Makefile2:630: recipe for target 'CMakeFiles/cartographer.mapping.internal.constraints.constraint_builder_3d_test.dir/all' failed
make[1]: *** [CMakeFiles/cartographer.mapping.internal.constraints.constraint_builder_3d_test.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
libcartographer.a(constraint_builder_2d.cc.o)：在函数‘cartographer::mapping::constraints::ConstraintBuilder2D::ComputeConstraint(cartographer::mapping::SubmapId const&, cartographer::mapping::Submap2D const*, cartographer::mapping::NodeId const&, bool, cartographer::mapping::TrajectoryNode::Data const*, cartographer::transform::Rigid2<double> const&, cartographer::mapping::constraints::ConstraintBuilder2D::SubmapScanMatcher const&, std::unique_ptr<cartographer::mapping::PoseGraphInterface::Constraint, std::default_delete<cartographer::mapping::PoseGraphInterface::Constraint> >*)’中：
constraint_builder_2d.cc:(.text+0x104e)：对‘ceres::Solver::Summary::Summary()’未定义的引用
libcartographer.a(ceres_scan_matcher_2d.cc.o)：在函数‘cartographer::mapping::scan_matching::CeresScanMatcher2D::Match(Eigen::Matrix<double, 2, 1, 0, 2, 1> const&, cartographer::transform::Rigid2<double> const&, std::vector<cartographer::sensor::RangefinderPoint, std::allocator<cartographer::sensor::RangefinderPoint> > const&, cartographer::mapping::Grid2D const&, cartographer::transform::Rigid2<double>*, ceres::Solver::Summary*) const’中：
ceres_scan_matcher_2d.cc:(.text+0x17a)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*)’未定义的引用
ceres_scan_matcher_2d.cc:(.text+0x245)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*)’未定义的引用
ceres_scan_matcher_2d.cc:(.text+0x30b)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*)’未定义的引用
libcartographer.a(ceres_scan_matcher_3d.cc.o)：在函数‘cartographer::mapping::scan_matching::CeresScanMatcher3D::Match(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, cartographer::transform::Rigid3<double> const&, std::vector<std::pair<std::vector<cartographer::sensor::RangefinderPoint, std::allocator<cartographer::sensor::RangefinderPoint> > const*, cartographer::mapping::HybridGrid const*>, std::allocator<std::pair<std::vector<cartographer::sensor::RangefinderPoint, std::allocator<cartographer::sensor::RangefinderPoint> > const*, cartographer::mapping::HybridGrid const*> > > const&, cartographer::transform::Rigid3<double>*, ceres::Solver::Summary*)’中：
ceres_scan_matcher_3d.cc:(.text+0x3b7)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*, double*)’未定义的引用
ceres_scan_matcher_3d.cc:(.text+0x5f4)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*)’未定义的引用
ceres_scan_matcher_3d.cc:(.text+0x6f7)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*)’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/cartographer.mapping.internal.constraints.constraint_builder_2d_test.dir/build.make:160: recipe for target 'cartographer.mapping.internal.constraints.constraint_builder_2d_test' failed
make[2]: *** [cartographer.mapping.internal.constraints.constraint_builder_2d_test] Error 1
CMakeFiles/Makefile2:670: recipe for target 'CMakeFiles/cartographer.mapping.internal.constraints.constraint_builder_2d_test.dir/all' failed
make[1]: *** [CMakeFiles/cartographer.mapping.internal.constraints.constraint_builder_2d_test.dir/all] Error 2
[ 67%] Linking CXX executable cartographer.mapping.internal.3d.scan_matching.interpolated_grid_test
[ 67%] Built target cartographer.mapping.internal.3d.scan_matching.interpolated_grid_test
[ 67%] Linking CXX executable cartographer.mapping.internal.3d.pose_graph_3d_test
libcartographer.a(constraint_builder_3d.cc.o)：在函数‘cartographer::mapping::constraints::ConstraintBuilder3D::ComputeConstraint(cartographer::mapping::SubmapId const&, cartographer::mapping::NodeId const&, bool, cartographer::mapping::TrajectoryNode::Data const*, cartographer::transform::Rigid3<double> const&, cartographer::transform::Rigid3<double> const&, cartographer::mapping::constraints::ConstraintBuilder3D::SubmapScanMatcher const&, std::unique_ptr<cartographer::mapping::PoseGraphInterface::Constraint, std::default_delete<cartographer::mapping::PoseGraphInterface::Constraint> >*)’中：
constraint_builder_3d.cc:(.text+0x12e0)：对‘ceres::Solver::Summary::Summary()’未定义的引用
libcartographer.a(optimization_problem_3d.cc.o)：在函数‘cartographer::mapping::optimization::(anonymous namespace)::AddLandmarkCostFunctions(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cartographer::mapping::PoseGraphInterface::LandmarkNode, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, cartographer::mapping::PoseGraphInterface::LandmarkNode> > > const&, cartographer::mapping::MapById<cartographer::mapping::NodeId, cartographer::mapping::optimization::NodeSpec3D> const&, cartographer::mapping::MapById<cartographer::mapping::NodeId, cartographer::mapping::optimization::CeresPose>*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cartographer::mapping::optimization::CeresPose, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, cartographer::mapping::optimization::CeresPose> > >*, ceres::Problem*, double) [clone .constprop.1731]’中：
optimization_problem_3d.cc:(.text+0x1837)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*, double*, double*, double*, double*, double*)’未定义的引用
libcartographer.a(optimization_problem_3d.cc.o)：在函数‘cartographer::mapping::optimization::OptimizationProblem3D::Solve(std::vector<cartographer::mapping::PoseGraphInterface::Constraint, std::allocator<cartographer::mapping::PoseGraphInterface::Constraint> > const&, std::map<int, cartographer::mapping::PoseGraphInterface::TrajectoryState, std::less<int>, std::allocator<std::pair<int const, cartographer::mapping::PoseGraphInterface::TrajectoryState> > > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cartographer::mapping::PoseGraphInterface::LandmarkNode, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, cartographer::mapping::PoseGraphInterface::LandmarkNode> > > const&)’中：
optimization_problem_3d.cc:(.text+0x3a83)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*, double*, double*, double*)’未定义的引用
optimization_problem_3d.cc:(.text+0x3ed9)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*, double*, double*, double*)’未定义的引用
optimization_problem_3d.cc:(.text+0x40d9)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*, double*, double*, double*)’未定义的引用
optimization_problem_3d.cc:(.text+0x4549)：对‘ceres::Solver::Summary::Summary()’未定义的引用
optimization_problem_3d.cc:(.text+0x472b)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*, double*, double*, double*)’未定义的引用
optimization_problem_3d.cc:(.text+0x6964)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*, double*, double*, double*, double*, double*)’未定义的引用
optimization_problem_3d.cc:(.text+0x6abd)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*, double*, double*)’未定义的引用
libcartographer.a(ceres_scan_matcher_3d.cc.o)：在函数‘cartographer::mapping::scan_matching::CeresScanMatcher3D::Match(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, cartographer::transform::Rigid3<double> const&, std::vector<std::pair<std::vector<cartographer::sensor::RangefinderPoint, std::allocator<cartographer::sensor::RangefinderPoint> > const*, cartographer::mapping::HybridGrid const*>, std::allocator<std::pair<std::vector<cartographer::sensor::RangefinderPoint, std::allocator<cartographer::sensor::RangefinderPoint> > const*, cartographer::mapping::HybridGrid const*> > > const&, cartographer::transform::Rigid3<double>*, ceres::Solver::Summary*)’中：
ceres_scan_matcher_3d.cc:(.text+0x3b7)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*, double*)’未定义的引用
ceres_scan_matcher_3d.cc:(.text+0x5f4)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*)’未定义的引用
ceres_scan_matcher_3d.cc:(.text+0x6f7)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*)’未定义的引用
libcartographer.a(ceres_scan_matcher_2d.cc.o)：在函数‘cartographer::mapping::scan_matching::CeresScanMatcher2D::Match(Eigen::Matrix<double, 2, 1, 0, 2, 1> const&, cartographer::transform::Rigid2<double> const&, std::vector<cartographer::sensor::RangefinderPoint, std::allocator<cartographer::sensor::RangefinderPoint> > const&, cartographer::mapping::Grid2D const&, cartographer::transform::Rigid2<double>*, ceres::Solver::Summary*) const’中：
ceres_scan_matcher_2d.cc:(.text+0x17a)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*)’未定义的引用
ceres_scan_matcher_2d.cc:(.text+0x245)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*)’未定义的引用
ceres_scan_matcher_2d.cc:(.text+0x30b)：对‘ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*)’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/cartographer.mapping.internal.3d.pose_graph_3d_test.dir/build.make:160: recipe for target 'cartographer.mapping.internal.3d.pose_graph_3d_test' failed
make[2]: *** [cartographer.mapping.internal.3d.pose_graph_3d_test] Error 1
CMakeFiles/Makefile2:710: recipe for target 'CMakeFiles/cartographer.mapping.internal.3d.pose_graph_3d_test.dir/all' failed
make[1]: *** [CMakeFiles/cartographer.mapping.internal.3d.pose_graph_3d_test.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
<== Failed to process package 'cartographer': 
  Command '['/home/nuc16/catkin_ws2019/devel_isolated/ceres-solver/env.sh', 'make', '-j4', '-l4']' returned non-zero exit status 2

Reproduce this error by running:
==> cd /home/nuc16/catkin_ws2019/build_isolated/cartographer && /home/nuc16/catkin_ws2019/devel_isolated/ceres-solver/env.sh make -j4 -l4

Command failed, exiting.

**Comment by MichaelGrupp** [comment]
I have updated the compilation instructions. Now it should work fine if you follow the instructions on a clean Ubuntu / ROS: https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html
