### ISSUE TITLE
Set initial pose for new trajectory based on "/map" frame in pure 3D localization mode 

### ISSUE THREAD

**Issue by tongtybj** [cartographer-project/cartographer_ros#1249]
I am trying  `rosrun cartographer_ros cartographer_start_trajectory` to set the initial pose for new trajectory in 3D map.

There are couple of troubles:
- "cartographer_start_trajectory" can set the initial pose based on the existing trajectory. Why there is no function to set the initial pose based on `/map` frame, which is much more straightforward and convenient for robot localization task (related issue: #989).
-  In 3D map mode, the poses in trajectory may not be level (i.e. roll and pitch are non zero). But the trajectory in `/trajectory_node_list` is composed from single points (means no orientation info). So it is very difficult to set the initial pose from the existing trajectory, leading to the bad localization performance. Is there any way to get the orientation information of trajectory?

**Comment by MichaelGrupp** [comment]
>  Is there any way to get the orientation information of trajectory?

I have an open pull request for a feature that might be helpful: https://github.com/googlecartographer/cartographer_ros/pull/1222
