### ISSUE TITLE
Running KITTI - Raw Data on cartographer, have problem in vehicle's pose

### ISSUE THREAD

**Issue by nobinov** [cartographer-project/cartographer_ros#1251]
Hi all! I'm new to cartographer and currently using it for my project in autonomous driving.

I am currently tried to run kitti dataset on cartographer_ros. I installed cartographer and cartographer_ros in early march.  I am using [Raw Data from data category Road](http://www.cvlibs.net/datasets/kitti/raw_data.php?type=road) which is [2011_10_03_drive_0042 (synced+rectified data)](https://s3.eu-central-1.amazonaws.com/avg-kitti/raw_data/2011_10_03_drive_0042/2011_10_03_drive_0042_sync.zip) and convert it to rosbag using [kitti2bag](https://github.com/tomas789/kitti2bag).

I slightly modified it to disable progressbar package. modified version of mine can be looked [here](https://github.com/nobinov/kitti_cartographer/blob/master/kitti2bag-mod.py). I should also mention that I did some extra modification to kitti2bag and pykitti because previously I use it to convert KITTI - Odometry dataset, which the modification can be looked at [issue at kitti2bag repo](https://github.com/tomas789/kitti2bag/issues/10#issuecomment-477147179) .

I checked my bag using `cartographer_rosbag-validate` and get this [output](https://gist.github.com/nobinov/8270a5aa3977c549f142b14d5ef5689b). I can't show the rosbag because it's too big (around 6.4 GB) to be uploaded.

To run it, I followed and adapted an example from [gmukitti](https://github.com/nobertgmuedu/gmukitti) and slightly edit some configuration to be compatible with current version of cartographer_ros. 

all the configurations (.lua, .urdf, .launch) can be looked at [https://github.com/nobinov/kitti_cartographer](url)

Apparently it can run, and can produce a map. However, it have a problem in the vehicle's pose. It seems it produce right orientation but have a wrong velocity. It resulted a "squished" map which screenshot of the generated map and path+constraints from rviz can be seen here : 
![Screenshot from 2019-04-05 15-51-56](https://user-images.githubusercontent.com/1491743/55632542-d3c5cd00-57ba-11e9-8ac2-605a54093afc.png)

Can anyone help what am I missing on here? Thank you :smile:

**Comment by MichaelGrupp** [comment]
I can't help with this configuration, but I'm pretty sure there are maybe other people have used Cartographer with KITTI before. https://www.youtube.com/watch?v=29Knm-phAyI
