### ISSUE TITLE
Lookup would require extrapolation at time. When trying 2D Cartographer ROS with a YD Lidar

### ISSUE THREAD

**Issue by mahendranicl** [cartographer-project/cartographer_ros#1253]
Hi,

I am trying to Run 2D Cartographer ROS with a YD Lidar. One error is ruining the performance of the move_base node, i.e. improper Robot navigation. 

It was working fine before in Ubuntu 14.04. When I upgraded the version to Ubuntu 16.04, I had to recompile my workspaces. 

Now when I run the 2D Cartographer ROS with a YD Lidar, I get the following error. 

[ WARN] [1554547766.837016521]: W0406 11:49:26.000000 19226 tf_bridge.cc:52] Lookup would require extrapolation at time 1554547766.814867700, but only time 1554547766.842371812 is in the buffer, when looking up transform from frame [laser_frame] to frame [base_link]

Thanks in advance !

**Comment by c66tang** [comment]
Hi, I ran into the same issue. Any updates on this?

**Comment by clement2449** [comment]
Hi, i have the same issue. It 's very anoying and there is nothing else about this problem on internet :(

**Comment by clement2449** [comment]
![Capture du 2019-05-14 10-29-47](https://user-images.githubusercontent.com/49431522/57683126-5dc34a00-7633-11e9-8175-0ac4ab62f051.png)

**Comment by mahendranicl** [comment]
Hi, 
I have solved the issue. It is to do with adjusting the pose update frequency, map update frequency, controller frequency parameters in both the move_base node configuration files and cartographer configuration files.

**Comment by clement2449** [comment]
@mahendranicl i understand what you would say but i don't want to find the correct value :( can you give me your lua file please with the value you have change it will really help me i think

**Comment by clement2449** [comment]
and your lidar file if you have change any value i am working on a lidar 7hz

**Comment by mahendranicl** [comment]
There are more than 3-4 files involved from various nodes. Will try to send

**Comment by clement2449** [comment]
@mahendranicl  thk you a lot i'm on it since 2 days ^^

**Comment by artemiialessandrini** [comment]
Hi @mahendranicl 
Did I get you right, that solution is to increase a frequency of several topics published?
