### ISSUE TITLE
Reset cartographer state during runtime of cartographer_node

### ISSUE THREAD

**Issue by DronistB** [cartographer-project/cartographer_ros#1255]
Hey,
Is there a way to reset cartographer node state without restarting the process(during runtime)?
(Reset the map)
Thanks

**Comment by MichaelGrupp** [comment]
I'm not entirely sure what you mean, but it could be related to something I want to implement:
Control over deleting and loading states during runtime, as proposed here: https://github.com/googlecartographer/rfcs/pull/41

**Comment by shirbarzel** [comment]
Restart all data related to cartographer(Map, Landmarks, subsmap etc)  just like restarting the process of cartographer node, without loading a pbstream file

**Comment by MichaelGrupp** [comment]
Completely resetting everything is currently not supported. My draft goes into this direction but is also not finished.
Regarding destruction, there was a similar request but it was not merged into master. You can follow up here: https://github.com/cartographer-project/cartographer/pull/1446

> Does the master version of cartographer is compatible with that version of cartographer_ros?

Nope. Only file backwards compatibility for pbstream.
