### ISSUE TITLE
Use of barometer with Cartographer?

### ISSUE THREAD

**Issue by lukehutch** [cartographer-project/cartographer_ros#1257]
I have a SLAM problem that is sensitive to altitude, and I would like to increase the accuracy of altitude with a barometer reading, since GNSS vertical resolution is poor, but I can't find any documentation on how to do that with Cartographer. Is it possible to correct for altitude drift using a barometer?

**Comment by MichaelGrupp** [comment]
There is no interface for using barometers as direct input.
