### ISSUE TITLE
In the robot running cartographer gives warning？   Queue duration: 0 s

### ISSUE THREAD

**Issue by MLeafs** [cartographer-project/cartographer_ros#1270]
Hi all,
  I have the following problem.
[ WARN] [1555678541.055529540]: W0419 20:55:41.000000  8980 fixed_ratio_sampler.cc:26] FixedRatioSampler is dropping all data.
[ INFO] [1555678541.325684094]: I0419 20:55:41.000000  8980 ordered_multi_queue.cc:172] All sensor data for trajectory 0 is available starting at '621355968000000000'.
[ WARN] [1555678541.338962556]: W0419 20:55:41.000000  8980 pose_extrapolator.cc:169] Queue too short for velocity estimation. Queue duration: 0 s
[ INFO] [1555678541.358460165]: I0419 20:55:41.000000  8980 pose_graph_2d.cc:147] Inserted submap (0, 0).
[ WARN] [1555678542.309645700]: W0419 20:55:42.000000  8980 pose_extrapolator.cc:169] Queue too short for velocity estimation. Queue duration: 0 s
[ WARN] [1555678543.344993589]: W0419 20:55:43.000000  8980 pose_extrapolator.cc:169] Queue too short for velocity estimation. Queue duration: 0 s

In that case I'm using this configuration

include "map_builder.lua"
include "trajectory_builder.lua"
options = {
  map_builder = MAP_BUILDER,
  trajectory_builder = TRAJECTORY_BUILDER,
  map_frame = "map",
  tracking_frame = "base_link",
  published_frame = "odom",
  odom_frame = "odom",
  provide_odom_frame = false,
  publish_frame_projected_to_2d = true,
  use_pose_extrapolator = true,
  use_odometry = false,
  use_nav_sat = false,
  use_landmarks = false,
  num_laser_scans = 0,
  num_multi_echo_laser_scans = 0,
  num_subdivisions_per_laser_scan = 1,
  num_point_clouds = 1,
  lookup_transform_timeout_sec = 0.2,
  submap_publish_period_sec = 0.3,
  pose_publish_period_sec = 5e-3,
  trajectory_publish_period_sec = 30e-3,
  rangefinder_sampling_ratio = 0.1,
  odometry_sampling_ratio = 0.1,
  fixed_frame_pose_sampling_ratio = 0.5,
  imu_sampling_ratio = 0,
  landmarks_sampling_ratio = 1.,
}
MAP_BUILDER.use_trajectory_builder_2d = true

TRAJECTORY_BUILDER_2D.submaps.num_range_data = 35
TRAJECTORY_BUILDER_2D.min_range = 0.3
TRAJECTORY_BUILDER_2D.max_range = 8.
TRAJECTORY_BUILDER_2D.missing_data_ray_length = 1.
TRAJECTORY_BUILDER_2D.use_imu_data = false
TRAJECTORY_BUILDER_2D.use_online_correlative_scan_matching = true
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.linear_search_window = 0.1
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.translation_delta_cost_weight = 10.
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.rotation_delta_cost_weight = 1e-1
POSE_GRAPH.optimization_problem.huber_scale = 1e2
POSE_GRAPH.optimize_every_n_nodes = 35
POSE_GRAPH.constraint_builder.min_score = 0.65
return options

  <param name="/use_sim_time" value="false" />

  <node name="cartographer_node" pkg="cartographer_ros"
      type="cartographer_node" args="
          -configuration_directory $(find cartographer_ros)/configuration_files
          -configuration_basename revo_lds.lua"
      output="screen">
   <remap from="points2" to="/rfans_points" />
<remap from="odom" to="/odom" />
  </node>
  <node name="cartographer_occupancy_grid_node" pkg="cartographer_ros"
      type="cartographer_occupancy_grid_node" args="-resolution 0.05" />

**Comment by gaschler** [comment]
Please post the *text* output of cartographer_rosbag_validate on your input data.

```
rangefinder_sampling_ratio = 0.1,
odometry_sampling_ratio = 0.1,
imu_sampling_ratio = 0,
```

Don't do this. It only hides issues with your input data and won't help.
