### ISSUE TITLE
set protobuf3 for cartographer_ros and there still exist protobuf2

### ISSUE THREAD

**Issue by crankler** [cartographer-project/cartographer_ros#1277]
I need protoc 2.6.1 for some ros packages, but now when I install cartigrapher on my computer,
there say I need to install protoc3, so I use this way to install protoc3.7 in /usr/protobuf
https://blog.csdn.net/qq_39024800/article/details/82751323
It's my test:
~$ protoc --version 
libprotoc 2.6.1

~$ protoc3.7 --version 
libprotoc 3.7.0

~$ whereis protoc
protoc: /usr/bin/protoc.bk /usr/bin/protoc /usr/local/bin/protoc3.7 /usr/local/bin/protoc /usr/share/man/man1/protoc.1.gz

And I also modify the CMakeLists.txt in cartographer as follow:
SET(PROTOBUF_DIR /usr/protobuf)
find_package(Protobuf 3 REQUIRED)

but when I compile use command:catkin_make_isolated --install --use-ninja
there still cannot find proto3.

So if I want to use protoc3 for cartographer and protoc2 for other ros package,
how can I set in cartographer package?
Thank you!!!

Error as follows:
[4/337] Running C++ protocol buffer co...apping/proto/2d/probability_grid.proto
FAILED: cd /home/hitnuc/cartographer_ros_ws/build_isolated/cartographer/install && /usr/local/bin/protoc --cpp_out /home/hitnuc/cartographer_ros_ws/build_isolated/cartographer/install -I /home/hitnuc/cartographer_ros_ws/src/cartographer /home/hitnuc/cartographer_ros_ws/src/cartographer/cartographer/mapping/proto/2d/probability_grid.proto
cartographer/mapping/proto/2d/probability_grid.proto:15:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
[4/337] Running C++ protocol buffer co...ommon/proto/ceres_solver_options.proto
FAILED: cd /home/hitnuc/cartographer_ros_ws/build_isolated/cartographer/install && /usr/local/bin/protoc --cpp_out /home/hitnuc/cartographer_ros_ws/build_isolated/cartographer/install -I /home/hitnuc/cartographer_ros_ws/src/cartographer /home/hitnuc/cartographer_ros_ws/src/cartographer/cartographer/common/proto/ceres_solver_options.proto
cartographer/common/proto/ceres_solver_options.proto:15:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
[4/337] Running C++ protocol buffer co...mapping/proto/2d/grid_2d_options.proto
FAILED: cd /home/hitnuc/cartographer_ros_ws/build_isolated/cartographer/install && /usr/local/bin/protoc --cpp_out /home/hitnuc/cartographer_ros_ws/build_isolated/cartographer/install -I /home/hitnuc/cartographer_ros_ws/src/cartographer /home/hitnuc/cartographer_ros_ws/src/cartographer/cartographer/mapping/proto/2d/grid_2d_options.proto
cartographer/mapping/proto/2d/grid_2d_options.proto:15:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
[4/337] Running C++ protocol buffer co...her/mapping/proto/2d/cell_limits.proto
FAILED: cd /home/hitnuc/cartographer_ros_ws/build_isolated/cartographer/install && /usr/local/bin/protoc --cpp_out /home/hitnuc/cartographer_ros_ws/build_isolated/cartographer/install -I /home/hitnuc/cartographer_ros_ws/src/cartographer /home/hitnuc/cartographer_ros_ws/src/cartographer/cartographer/mapping/proto/2d/cell_limits.proto
cartographer/mapping/proto/2d/cell_limits.proto:15:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
ninja: build stopped: subcommand failed.
<== Failed to process package 'cartographer': 
  Command '['/home/hitnuc/cartographer_ros_ws/install_isolated/env.sh', 'ninja', '-j4', '-l4']' returned non-zero exit status 1

Reproduce this error by running:
==> cd /home/hitnuc/cartographer_ros_ws/build_isolated/cartographer && /home/hitnuc/cartographer_ros_ws/install_isolated/env.sh ninja -j4 -l4

**Comment by gaschler** [comment]
You don't need to install protobuf in the system to use it in Cartographer.
One way to edit the cmake settings is using `ccmake` in the build folder.
Once you know all the settings to change, you can later specify `-D...=...` arguments to catkin that are passed to cmake.
The tricky thing is when having multiple protobuf versions,
you must use the exact matching versions of protobuf compiler, header files and libraries and not mix versions.

**Comment by crankler** [comment]
Thank you for your reply!
So can you tell me the detail setting on this package!

**Comment by ojura** [comment]
@gaschler a much better alternative is to set `CMAKE_PREFIX_PATH` to the install location of Protobuf 3 and let `find_package(Protobuf)` set up everything, instead of manually setting all CMake variables using `-DPROTOBUF_..`.

**Comment by MichaelGrupp** [comment]
@ojura's approach looks good. On newer Ubuntu versions, I would recommend to use just the version that is installed via rosdep. The build documentation was also changed accordingly.
