### ISSUE TITLE
catkin make error

### ISSUE THREAD

**Issue by CherryChenw** [cartographer-project/cartographer_ros#1281]
when I catkin_make。I got this as follow：
[  2%] Building CXX object cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/cartographer_ros/submap.cc.o
[  5%] Building CXX object cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/cartographer_ros/tf_bridge.cc.o
[  7%] Building CXX object cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/cartographer_ros/msg_conversion.cc.o
[ 10%] Building CXX object cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/cartographer_ros/urdf_reader.cc.o
[ 12%] Building CXX object cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/cartographer_ros/sensor_bridge.cc.o
[ 15%] Building CXX object cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/cartographer_ros/trajectory_options.cc.o
In file included from /home/nvidia/pjm_catkin_workplace/src/cartographer_ros/cartographer_ros/cartographer_ros/trajectory_options.cc:17:0:
/home/nvidia/pjm_catkin_workplace/src/cartographer_ros/cartographer_ros/cartographer_ros/trajectory_options.h:25:53: fatal error: cartographer_ros_msgs/TrajectoryOptions.h: No such file or directory
compilation terminated.
cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/build.make:254: recipe for target 'cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/cartographer_ros/trajectory_options.cc.o' failed
make[2]: *** [cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/cartographer_ros/trajectory_options.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/nvidia/pjm_catkin_workplace/src/cartographer_ros/cartographer_ros/cartographer_ros/tf_bridge.cc:19:0:
/home/nvidia/pjm_catkin_workplace/src/cartographer_ros/cartographer_ros/cartographer_ros/msg_conversion.h:26:48: fatal error: cartographer_ros_msgs/LandmarkList.h: No such file or directory
compilation terminated.
cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/build.make:206: recipe for target 'cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/cartographer_ros/tf_bridge.cc.o' failed
make[2]: *** [cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/cartographer_ros/tf_bridge.cc.o] Error 1
In file included from /home/nvidia/pjm_catkin_workplace/src/cartographer_ros/cartographer_ros/cartographer_ros/msg_conversion.cc:17:0:
/home/nvidia/pjm_catkin_workplace/src/cartographer_ros/cartographer_ros/cartographer_ros/msg_conversion.h:26:48: fatal error: cartographer_ros_msgs/LandmarkList.h: No such file or directory
compilation terminated.
cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/build.make:182: recipe for target 'cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/cartographer_ros/msg_conversion.cc.o' failed
make[2]: *** [cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/cartographer_ros/msg_conversion.cc.o] Error 1
In file included from /home/nvidia/pjm_catkin_workplace/src/cartographer_ros/cartographer_ros/cartographer_ros/submap.cc:22:0:
/home/nvidia/pjm_catkin_workplace/src/cartographer_ros/cartographer_ros/cartographer_ros/msg_conversion.h:26:48: fatal error: cartographer_ros_msgs/LandmarkList.h: No such file or directory
compilation terminated.
cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/build.make:134: recipe for target 'cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/cartographer_ros/submap.cc.o' failed
make[2]: *** [cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/cartographer_ros/submap.cc.o] Error 1
In file included from /home/nvidia/pjm_catkin_workplace/src/cartographer_ros/cartographer_ros/cartographer_ros/urdf_reader.cc:22:0:
/home/nvidia/pjm_catkin_workplace/src/cartographer_ros/cartographer_ros/cartographer_ros/msg_conversion.h:26:48: fatal error: cartographer_ros_msgs/LandmarkList.h: No such file or directory
compilation terminated.
cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/build.make:86: recipe for target 'cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/cartographer_ros/urdf_reader.cc.o' failed
make[2]: *** [cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/cartographer_ros/urdf_reader.cc.o] Error 1
In file included from /home/nvidia/pjm_catkin_workplace/src/cartographer_ros/cartographer_ros/cartographer_ros/sensor_bridge.cc:17:0:
/home/nvidia/pjm_catkin_workplace/src/cartographer_ros/cartographer_ros/cartographer_ros/sensor_bridge.h:29:48: fatal error: cartographer_ros_msgs/LandmarkList.h: No such file or directory
compilation terminated.
cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/build.make:230: recipe for target 'cartographer_ros/cartographer_ros/CMakeFiles/cartographer_ros.dir/cartographer_ros/sensor_bridge.cc.o' failed

how to solve this problem？

**Comment by gaschler** [comment]
Build cartographer_ros_msgs first
