### ISSUE TITLE
How to track the changes of the map after loop closing?

### ISSUE THREAD

**Issue by mojovski** [cartographer-project/cartographer_ros#1291]
When I define points of interest on the map (POIs) represented by a coordinate (x,y) I am afraid of its movement on the map after cartographer performs a loop closure.

## Questions: 
* How can I disable map changes after a map has been stored via write_state ?
* If its not possible, how can I track the changes so I know that (x1,y1) needs to be updated on (x2,y2) after a loop closure?

**Comment by MichaelGrupp** [comment]
> How can I disable map changes after a map has been stored via write_state ?

Load it as frozen state in the node

> If its not possible, how can I track the changes so I know that (x1,y1) needs to be updated on (x2,y2) after a loop closure?

This would be only possible if your POIs are defined relative to a trajectory node, like landmarks.
