### ISSUE TITLE
Online Evaluation of Covariance by Pose Relations Metric

### ISSUE THREAD

**Issue by Ly0n** [cartographer-project/cartographer_ros#1299]
I try to calculate the covariance of the cartographer LocalSLAM for the fusion into robot_localisation with some low cost RTK and my wheel odometry.
The robot is used inside a know limit area that can be pre-mapped. 
In many other issues I read, that the calculation of a meaningful covariance is not that simple for SLAM. But this is already done inside the cartographer_autogenerate_ground_truth tool from my point of view:
```
Abs translational error 0.01944 +/- 0.01819 m
Sqr translational error 0.00071 +/- 0.00189 m^2
Abs rotational error 0.11197 +/- 0.12432 deg
Sqr rotational error 0.02799 +/- 0.07604 deg^2
```
https://google-cartographer.readthedocs.io/en/latest/evaluation.html?highlight=metric

Would it be possible to create the covariance online from a pre-created map?

**Comment by 3473f** [comment]
@Ly0n I am not sure if you are still looking for it, but I experimented with the covariance computation for the scan matcher using the methods provided by the ceres solver [1], but it didn't seem to show any interesting characteristics (i.e. no observed elongation in long corridor test for example) so I had to ditch this approach completely.

Also, previous versions of the cartographer was using the covariance, but it was removed as it was computationally expensive and didn't show any performance gain. [2]

[1] http://ceres-solver.org/nnls_covariance.html
[2] https://github.com/cartographer-project/cartographer/commit/a2e52f81cfde4e3a4a6e751af4eb2d9c51354c36
