### ISSUE TITLE
Export scan_matched_points2

### ISSUE THREAD

**Issue by athtest800** [cartographer-project/cartographer_ros#1307]
Hi!
I want to export the "scan_matched_points2" but with the calculated corrected poses and loop closed.
I do not want to use the offline method for .ply, because I get noisy results with this.
Is there methodology for this?

**Comment by athtest800** [comment]
Is it possible to timestamp scan_matched_points2 with timestamps from scanning time?

**Comment by Sanderi44** [comment]
You could record scan_matched_points2 into a bag file.  It should have timestamps in the header of each PointCloud2 message.

**Comment by MichaelGrupp** [comment]
The scan matched points is more suitable for debugging visualization and probably not reliable for making good point clouds.
