### ISSUE TITLE
i do not save yaml file

### ISSUE THREAD

**Issue by ytgcljj** [cartographer-project/cartographer_ros#1309]
nuc7@nuc7:~/catkin_ws/install_isolated/share/cartographer_ros/maps$ rosrun  cartographer_ros cartographer_pbstream_to_ros_map -pbstream_filename=~/catkin_ws/install_isolated/share/cartographer_ros/maps/zl.pbstream  -map_filestem=~/111
F0604 17:19:42.455739  7087 pbstream_to_ros_map_main.cc:47] Check failed: reader.ReadProto(&pose_graph) 
*** Check failure stack trace: ***
    @     0x7fa36f1195cd  google::LogMessage::Fail()
    @     0x7fa36f11b433  google::LogMessage::SendToLog()
    @     0x7fa36f11915b  google::LogMessage::Flush()
    @     0x7fa36f11be1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x4be357  cartographer_ros::(anonymous namespace)::Run()
    @           0x4bc9b8  main
    @     0x7fa36d926830  __libc_start_main
    @           0x4bdd39  _start
    @              (nil)  (unknown)
已放弃

**Comment by artemiialessandrini** [comment]
#1292
