### ISSUE TITLE
My pure location model cannot work well

### ISSUE THREAD

**Issue by Zacharyzqc** [cartographer-project/cartographer_ros#1322]
1. run `rosbag_validate`  
 and got the message 'Point data (frame_id: "rslidar") has a large gap, largest is 0.102116 s, recommended is [0.0005, 0.05] s with no jitter'. How can I improve it
2. the setting files link : [files](https://github.com/Zacharyzqc/cartographer-settings)
3.the pic,we can see that the lidar points cannot match the map suitable
![cut1](https://user-images.githubusercontent.com/41284846/59500202-8a38e300-8ecb-11e9-83c9-c07f74bf62fc.png)

**Comment by CherryChenw** [comment]
mybag is the same error to you，and I can't see anything when I running with rslidar and imu。
[ WARN] [1563854413.115772888]: W0723 12:00:13.000000  5669 ordered_multi_queue.cc:155] Queue waiting for data: (0, points2)
 Have you seen the same question？

**Comment by MichaelGrupp** [comment]
Closing as inactive. We can't help with tuning this custom setup unfortunately.
