### ISSUE TITLE
Error timestamp whem loking up transformation froù frame os1_lidar to base_link

### ISSUE THREAD

**Issue by hachbani2019** [cartographer-project/cartographer_ros#1324]
Hi,

I'm trying to build a 3D map from bag file I did record using an Ouster 3D 64 Lidar. 

I did post an earlier issue: #1315. After finding the bug in my code, i'm encountring a new issue now. When I run  `$ roslaunch cartographer_ros demo_my_robot.launch bag_filename:=/home/hamza/Documents/bags_ouster/2019-05-10-11-00-03.bag ` I get the following WARN message and nothing displayed on Rviz.

`[ WARN] [1560517683.588274768, 1557478806.020221075]: W0614 15:08:03.000000 23713 tf_bridge.cc:52] Lookup would require extrapolation into the past.  Requested time 91.991037300 but the earliest data is at time 1557478803.561839041, when looking up transform from frame [os1_lidar] to frame [base_link]`

here's a screenshot of a part of the error messages: https://imgur.com/a/iobRpe9

my Tf_tree and rqt_graph are the same as in #1315. My launch and lua files are here: https://github.com/hachbani2019/Cartographer.git

Any help please ?

**Comment by tyuownu** [comment]
Hi, you need to build the URDF(replace backpack_3d.urdf with you urdf file) file for you model, so that it can find correct tf transform.
