### ISSUE TITLE
Any plan for a new release?

### ISSUE THREAD

**Issue by seanyen** [cartographer-project/cartographer_ros#1327]
It's been a year since the `v1.0` release and there are so many commits in the past year. Any plan to make another release?

**Comment by xperroni** [comment]
I second that, if only to make the latest version up-to-date with the documentation — some features mentioned in the [ROS API reference](https://google-cartographer-ros.readthedocs.io/en/latest/ros_api.html) (for example, the `get_trajectory_states` service) are not implemented in the 1.0.0 release.

**Comment by MichaelGrupp** [comment]
Duplicate of #1512
