### ISSUE TITLE
No reference to pre-built packages available from packages.ros.org

### ISSUE THREAD

**Issue by razorheadfx** [cartographer-project/cartographer_ros#1335]
There is [plenty of documentation on building cartographer_ros](https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html#building-installation from source) which is good if you want to life on the bleeding edge.
But building from source is a little much if you just want to check out  the demos.
Unfortunately neither the README nor the readthedocs indicates that there are pre-built packages available from [packages.ros.org](https://index.ros.org/search/?term=cartographer_ros).

Including a link to a search in the index within the README  and readthedocs could improve visibility and ease of use for beginners.

**Comment by MichaelGrupp** [comment]
Good point. The packages are currently a bit outdated so I want to wait until we have a newer release. #1512
