### ISSUE TITLE
Optimization hangs for long periods of time

### ISSUE THREAD

**Issue by santosj** [cartographer-project/cartographer_ros#1337]
I am experiencing a similar behavior as documented in #247. I have followed all the solutions mentioned in #247, such as the cmake build type set to "Release" and I have checked if all the dependencies are correctly installed such as  `libatlas-base-dev` and `libsuitesparse-dev` and when the bag stops playing, the optimization can last up to 30 minutes. If i try to finish the trajectory by calling the service `rosservice call /finish_trajectory "trajectory_id: 0"`, I get the result `Trajectory 0 already pending to finish.` endlessly.  I have noticed that this does not happen when running the same setup with release 1.0.0, in that case the optimization is done quite fast and the service to finish the trajectory does not hang.

1. the output of `rosbag_validate` can be found here: https://gist.github.com/santosj/cb0f3937962e5e8b31377781d5492c39

2. I have uploaded launch file, configuration file and rosbag to: https://drive.google.com/drive/folders/1LbXY6mQHCs1l2vCKURQ3kxkPcaKQSxbZ?usp=sharing

Thanks in advance.

**Comment by MichaelGrupp** [comment]
Usually it helps to decrease some sampling ratios, e.g. of the constraint builder. A good guide is here: https://google-cartographer-ros.readthedocs.io/en/latest/tuning.html#low-latency
