### ISSUE TITLE
Wall disappears in 2D SLAM

### ISSUE THREAD

**Issue by wkwkw** [cartographer-project/cartographer_ros#1338]
I'm trying cartographer's 2D SLAM and met the problem that the wall, which once has been recognized, be disappeared when the robot returns.

It had not been happend with Gmapping, so I want the cartographer's result to be the same level.

* cartographer
![cartographer](https://user-images.githubusercontent.com/16659487/60261630-4a381e00-9917-11e9-86d9-9649dda9a150.png)
* gmapping
![gmapping](https://user-images.githubusercontent.com/16659487/60261636-4c01e180-9917-11e9-8cab-50eddf8d29c4.png)
* photo of the area, taken from the entrance, left side in the upper images (the way is about 1m wide): 
![locker1](https://user-images.githubusercontent.com/16659487/60261640-4efcd200-9917-11e9-9fee-b6356c09a49a.png)

How can I fix this?

I think the wall's smooth surface is causing problem (It may be hard to recognize for laser sensor).
But I believe the effect can be mitigated in software side.

Sensors: 
* 2D laser sensor (/scan)
* wheel odometry (/odom)
* IMU (/imu)

[forked repo](https://github.com/wkwkw/cartographer_ros.git)
[bagfile](https://github.com/wkwkw/tmp/blob/master/carto_files/locker_area.bag)
[result of rosbag_validate](https://gist.github.com/wkwkw/bd16c68e35ebfd9fceca6fe474debaec)

Thanks in advance for your help!

**Comment by MichaelGrupp** [comment]
I'd look at the submaps display instead of occupancy grid, The occupancy grid node of Cartographer just blends all submaps into an image, so it could be that it just _looks_ as if the wall is gone.

The submaps plugin of cartographer_rviz is able to show you the individual submaps instead, which might be better for checking the result here. Note that you also have similar laser artifacts ("spray" of free space) in the gmapping result, maybe because of the reflective (?) surface of your walls.

**Comment by wkwkw** [comment]
Thanks for the response.

First, I checked the individual submaps on rviz and found that the first submap, no 0, still holds the wall and others don't. I show the all submaps below (total 6 with default _num_range_data_ =90).

Is there a way to use the better result of the submap in navigating the robot? (I'm considering to use the Navigation Stack)

0 ![image](https://user-images.githubusercontent.com/16659487/60776760-6df63200-a169-11e9-8a3b-4a5708284410.png)
1 ![image](https://user-images.githubusercontent.com/16659487/60776782-849c8900-a169-11e9-9973-e513e5687da4.png)
2 ![image](https://user-images.githubusercontent.com/16659487/60776828-d8a76d80-a169-11e9-939a-e1cc78d4cce6.png)
3 ![image](https://user-images.githubusercontent.com/16659487/60776798-a0a02a80-a169-11e9-8d4d-d5474ad11840.png)
4 ![image](https://user-images.githubusercontent.com/16659487/60776802-ad248300-a169-11e9-9675-309d8276bc57.png)
5 ![image](https://user-images.githubusercontent.com/16659487/60776808-b9a8db80-a169-11e9-8017-a4de59bb35c9.png)


Second, as you mentioned, "spray" of free space can also be found in gmapping result (and also in the result of official data checker tool of HOKUYO) and I think it's caused by the reflective surface. 

I guess gmapping tends to keep what is recognized to be a wall as a wall and cartographer not.
It seems to be a tradeoff between erasing what have to be kept and failing to erase what have to be erased.

p.s.
I found that setting _max_range_ to around 5m reduces the probrem, but I want to utilize the 20m view range of the sensor (HOKUYO UST-20LX-H01).

**Comment by Yu-Xiaoxian** [comment]
@wkwkw for the reflective surface, I suggest to filter some points based on their intensity.

**Comment by Yu-Xiaoxian** [comment]
@wkwkw I am interested to hear that you are using Hokuyo lidar, have you ever confused by the problem that this lidar get inaccurate at near distance(0.2m - 1.0m)?

**Comment by wkwkw** [comment]
@Yu-Xiaoxian Hi, I've just been trying the way you mentioned and getting better results.
I'm now feeling more confident in taking this way by your reply, thank you.
> @wkwkw for the reflective surface, I suggest to filter some points based on their intensity.


And for the question about Hokuyo lidar, no. I've never been met a problem by the inaccurateness at near distance so far.

**Comment by Yu-Xiaoxian** [comment]
@wkwkw great, I'm glad to hear you making progress. Thanks for your info about the Hokuyo Lidar, I will contact my supplier for a solution.
