### ISSUE TITLE
How to stitch multiple maps and .pbstream files together for a larger scene

### ISSUE THREAD

**Issue by FeynH** [cartographer-project/cartographer_ros#1342]
Hi, I am trying to build a 2D map of a big scene (it is about 250m x 250m). But I am worried that my equipment can't afford to build such a large map at once. So I want to build a smaller map each time, and then stitch these small maps together to get the whole big map. At the same time, I want to put together the pbstream files for positioning.
So I wander how to stitch multiple maps and .pbstream files together for a larger scene

**Comment by MichaelGrupp** [comment]
This is something that is theoretically possible, but we don't provide a tool for this at the moment.
