### ISSUE TITLE
Configuration and loop closure problems in 2d 

### ISSUE THREAD

**Issue by carl1218** [cartographer-project/cartographer_ros#1344]
Hi,
     I can't make the good result using real time processing data in 2d lidar slam.
     I only used one lidar to tried to build a map using real time, but the position not correct (when the  returned to starting point) and make cartographer failed to make a loop closure.

   A loop-closed map with significant overlap,look like this:
<img width="461" alt="slam" src="https://user-images.githubusercontent.com/17962046/60534733-130da680-9d35-11e9-82ac-40bd50ced4fa.png">

This is rosbag_validate:
https://drive.google.com/file/d/1_fxwQpjrkmIfnYmtMBrjK0V6gmU6BP5v/view?usp=sharing
This is my bag:
https://drive.google.com/file/d/1pnh9qWLLCOwKvSqlZ3cymC5ixb6Gbmdh/view?usp=sharing
This is lua:
https://drive.google.com/file/d/1UapH0d80SXHOfGMS01-KvsJCmyMspn4n/view?usp=sharing
This is launch:
https://drive.google.com/file/d/1RLAbbk1HHL2dycQ8jzbKIh5URlo2YqUS/view?usp=sharing

**Comment by BryanYu1909** [comment]
Hello, do you get a solution, I am facing a similiar issue

**Comment by MichaelGrupp** [comment]
You should tune local SLAM first, it drifts a lot. And maybe then adapt the loop closure search radius.
