### ISSUE TITLE
The issue of Remaining work items in queue

### ISSUE THREAD

**Issue by huangshuqing** [cartographer-project/cartographer_ros#1361]
Hello，
I use a VLP16 laser and a xsens imu. when I run cartographer 3D with pure Localization in a Given Map, I always meet the issue of remaining work items in queue，such as "Remaining work items in queue: 17893". The size of queue frequently reaches tens of thousands. From my personal point of view, If the parameters are tuned well, the value should be 0. However, How can I continue to tune the parameters, can you give me some advice?

**Comment by MichaelGrupp** [comment]
See https://google-cartographer-ros.readthedocs.io/en/latest/tuning.html#low-latency
