### ISSUE TITLE
Using raw IMU data into cartographer_ros

### ISSUE THREAD

**Issue by JaredLee1218** [cartographer-project/cartographer_ros#1364]
My IMU is 'EBIMU-9DOFV4' from e2box company

I've never seen this imu according to cartographer_ros. ROS did not support this imu.

SO i published IMU node, and made imu topic.

However, I just want to make IMU data fit to cartographer_ros...

Here is my IMU data

rostopic echo imu
![imudata](https://user-images.githubusercontent.com/52229587/61508130-86950080-aa23-11e9-9305-b2aa2ab95a11.png)

How can I change data to this?
http://docs.ros.org/api/sensor_msgs/html/msg/Imu.html

**Comment by nhphuong91** [comment]
Try to read the IMU datasheet/example for understanding what these number are. Then write a node (or other similar way) to extract this data out and manipulate it following sensor_msgs/Imu format and publish it to topic /imu. Have fun!
