### ISSUE TITLE
How to  save or delete specific trajectory?

### ISSUE THREAD

**Issue by robot-mh** [cartographer-project/cartographer_ros#1373]
After run cartographer_ros node and _write_state_, _load_state_filename_ multi times, I have 0~5 trajectory in file map.pbstream.

How can I delete trajectory 0~4, only reserve the last trajectory 5?

or how to save specific trajectory use _write_state_？

thank you guys. @SirVer @esteve @damienrg @damonkohler @skohlbr

**Comment by ShihanWang** [comment]
I have the same question. I think we should change the WritePbSteam function code: 
delete old trojectory data in PoseGraph: constraints、submaps、Nodes...

**Comment by ShihanWang** [comment]
this may be useful to solve it:
[https://github.com/googlecartographer/cartographer/issues/1474](url)

**Comment by ShihanWang** [comment]
I changed the WritePbStream function code, and just save the specific trajectory with its trajectory_id=0, at the same time, remap all the constraints、submaps、nodes、imu_data、odometry_data. But deleting a specific trajectory is more complicated...

**Comment by MichaelGrupp** [comment]
There is a pull request with a concept draft for that in the RFC repository. But it's not implemented here yet.

**Comment by GrantZheng86** [comment]
Hi @ShihanWang,

Do you know where is the "WritePbStream" function located? I'm trying to do a similar thing.

Thanks!
