### ISSUE TITLE
cartographer_node immediately crashes in Eloquent due to --ros-args

### ISSUE THREAD

**Issue by rotu** [cartographer-project/cartographer_ros#1378]
If you launch cartographer_node from a launch file in ROS2 Eloquent, it immediately crashes because of the new `--ros-args` command line flag introduced in https://github.com/ros2/launch_ros/pull/52

```
$ ros2 launch openrover_demo slam.launch.py 
[INFO] [launch]: All log files can be found below /home/dan/.ros/log/2019-08-26-12-53-21-490738-rhea-17163
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [cartographer_node-1]: process started with pid [17174]
[INFO] [occupancy_grid_node-2]: process started with pid [17175]
[occupancy_grid_node-2] ERROR: unknown command line flag 'ros-args'
[ERROR] [occupancy_grid_node-2]: process has died [pid 17175, exit code 1, cmd '/home/dan/ros2_ws/install/lib/cartographer_ros/occupancy_grid_node -resolution 0.02 -publish_period_sec 1.0 --ros-args'].
[cartographer_node-1] ERROR: unknown command line flag 'ros-args'
[ERROR] [cartographer_node-1]: process has died [pid 17174, exit code 1, cmd '/home/dan/ros2_ws/install/lib/cartographer_ros/cartographer_node -configuration_directory /home/dan/ros2_ws/install/share/openrover_demo/config 
```

**Comment by MichaelGrupp** [comment]
See linked issue. A proper up to date ROS2 port is planned here, FYI. See also my comment here: #1515

**Comment by rotu** [comment]
@MichaelGrupp why did you close this? It appears to still be an open issue.

**Comment by MichaelGrupp** [comment]
Because the current ROS2 port resides in a fork that is not maintained by us. If the ROS2 API was broken in a way that crashes your use case, I would recommend to complain in the respective repos.

We are, together with the ROS2 guys, aware of the problem that this fork is super outdated. That's why we from the Cartographer side rather want to invest time in a proper port (ETA unknown currently as I said) and don't support the current port.

**Comment by rotu** [comment]
Thanks, @MichaelGrupp! Maybe it would make sense to archive this repo or create a prominent pointer to the authoritative fork (presumably https://github.com/ros2/cartographer_ros)

**Comment by MichaelGrupp** [comment]
No, _this_ repo here (cartographer-project) is the official one, but it has no ROS2 port yet. The forked repo (ros2) has a ROS2 port that you are using right now, but is outdated. The next working version of cartographer for ROS2 is planned to be built here (cartographer-project).
