### ISSUE TITLE
Documentation backpack_2d.lua error

### ISSUE THREAD

**Issue by jonra1993** [cartographer-project/cartographer_ros#1382]
Hi I was looking at documentation and I found a mistake. In 2D SLAM, lua file should be backpack_2d.lua instead of backpack_3d.lua. I see in github docs that mistake is solved but in readthedocs.io it persists.

![image](https://user-images.githubusercontent.com/23468720/64030231-c44d7480-cb0b-11e9-9cd5-518ac50c6049.png)

**Comment by MichaelGrupp** [comment]
Fixed, the readthedocs part is now up to date with master again.
