### ISSUE TITLE
OccupancyGrid nav msg faster update

### ISSUE THREAD

**Issue by StevenvanLeeuwen** [cartographer-project/cartographer_ros#1387]
How would I publish to the map topic a nav msg faster than using the OccupancyGrid node? 
My idea is to use only the current submap to publish to this topic, how would I do this?

**Comment by MichaelGrupp** [comment]
This would be something that you need to add to `node.cc` in your fork. It should be possible to fetch a submap and publish it similar to what the occ. grid node does.
