### ISSUE TITLE
Could I run Cartographer using PointCloud2 Without IMU?

### ISSUE THREAD

**Issue by Paumila** [cartographer-project/cartographer_ros#1400]
Hello,

I am new on Cartographer and I have one question. 

There is an option to run Cartographer using a 3D camera such as Kinect (pointcloud2) without using the IMU?

I would like to know if there is an option or I need to use a IMU with pointcloud2. If does not exist a solution for this question, which could be the best option?

Sorry, it is my first post in github.

**Comment by MrGitGo** [comment]
Yes, you can use your Kinect without IMU. But you have to use the 2d cartographer mode.

**Comment by MichaelGrupp** [comment]
https://google-cartographer-ros.readthedocs.io/en/latest/faq.html#why-is-imu-data-required-for-3d-slam-but-not-for-2d
