### ISSUE TITLE
What does I need for Slam mapping with only one rplidar?

### ISSUE THREAD

**Issue by aminballoon** [cartographer-project/cartographer_ros#1407]
1. How to make file .bag with Node /scan
2. How to setting .lua file
3. How to setting launch file

**Comment by artemiialessandrini** [comment]
I'd recommend to start from:
[Cartographer Wiki Page](https://google-cartographer-ros.readthedocs.io/en/latest/index.html) and adopt launch files already existing
[ROS Wiki page](http://wiki.ros.org/ROS/Tutorials), detailed [.bag files recording tutorial](http://wiki.ros.org/ROS/Tutorials/Recording%20and%20playing%20back%20data) :)
