### ISSUE TITLE
I cant make mapping from Cartographer

### ISSUE THREAD

**Issue by aminballoon** [cartographer-project/cartographer_ros#1408]
I don't have how to solve this error 
https://drive.google.com/open?id=1uH-Ih0qr4md0R9Ns_FFysMqu5_YuA3dx
this link have my .lua .launch and rqt_graph

**Comment by nerellasureshkumar7** [comment]
Hi,
   Please check your frame_id of the laser_scan. By default link(laser sensor) name and frame_id of the sensor should be same. Try to change it and test. It will be more useful if you post the bag file.

**Comment by aminballoon** [comment]
> Hi,
> Please check your frame_id of the laser_scan. By default link(laser sensor) name and frame_id of the sensor should be same. Try to change it and test. It will be more useful if you post the bag file.

Sorry i dont used .bag file my station have only one rplidar

**Comment by nerellasureshkumar7** [comment]
> > Hi,
> > Please check your frame_id of the laser_scan. By default link(laser sensor) name and frame_id of the sensor should be same. Try to change it and test. It will be more useful if you post the bag file.
> 
> Sorry i dont used .bag file my station have only one rplidar

OK. Change the frame_id and test

**Comment by aminballoon** [comment]
> > > Hi,
> > > Please check your frame_id of the laser_scan. By default link(laser sensor) name and frame_id of the sensor should be same. Try to change it and test. It will be more useful if you post the bag file.
> > 
> > 
> > Sorry i dont used .bag file my station have only one rplidar
> 
> OK. Change the frame_id and test

Can you tell me how to Chage name frame_id  I'm beginner for ros sorry
