### ISSUE TITLE
Robot position doesn't update when simulation is reset

### ISSUE THREAD

**Issue by FrancescoTerrosi** [cartographer-project/cartographer_ros#1410]
Hello,
I think the title says it all.

I am using ros-melodic and gazebo-9 to train a turtlebot using both laser data and slam map.
I reset the simulation every time the turtlebot reaches the goal or it collides with something, when this happens cartographer is not able to update the robot position and the map gets screwed up. I will attach some pictures for a better comprehension

Before simulation reset:

![Before simulation reset](https://user-images.githubusercontent.com/33395865/67978603-6a078780-fc12-11e9-81ef-07ec6208bfaf.png)

After simulation reset:

![After simulation reset](https://user-images.githubusercontent.com/33395865/67978620-768be000-fc12-11e9-98e0-29143d73704d.png)

Position update warning:

![Position update fail warning](https://user-images.githubusercontent.com/33395865/67978639-7db2ee00-fc12-11e9-84fb-313ced5fad70.png)

**Comment by neomanic** [comment]
Are you creating a new trajectory in Cartographer when you reset the simulation?
