### ISSUE TITLE
cartographer node cannot subscribe to point cloud and generate map.

### ISSUE THREAD

**Issue by saharLeisiazar** [cartographer-project/cartographer_ros#1414]
Hi

I am using 3D ouster lidar and xsens IMU. when I launch either online or demo launch file, the cartographer node can subscribe to both IMU and pointclouds but cannot generate map. both topics seem fine. I would appreciate it if some one can help me.

Here is the error:
https://gist.github.com/saharLeisiazar/0397fb85c446f369074e1644aaa5fa6f

and cartographer_rosbag_validate results:
cartographer_rosbag_validate -bag_filename topics.bag
https://gist.github.com/saharLeisiazar/aa8ce34bc3b8af191bed72887969ed71

four files are uploaded here:
https://github.com/saharLeisiazar/cartographer_ros/tree/master/cartographer_ros
files are: my_robot.launch, demo_3d.launch, my_robot.urdf, my_robot.lua

the bag file is uploaded here:
https://drive.google.com/file/d/1fcx61YRRtdcuyb_fZtc9rmAEHOOoQxJm/view?usp=sharing

**Comment by MichaelGrupp** [comment]
You probably need to do a topic remap in your launch file (ROS documentation) from the name of the pointcloud topic in your bag to `points2`, which is the name that Cartographer is expecting.
