### ISSUE TITLE
cartographer3d  gray ground and imu correction issue

### ISSUE THREAD

**Issue by Fanny-one** [cartographer-project/cartographer_ros#1426]
1. Hi, @gaschler @ojura
I have try cartographer_2d and cartographer_3d  in my project. Both can produce good map, but I find the free zone or ground using cartographer_3d is gray instead white.  The first picture is from cartographer_2d and another is from cartographer_3d.
![scan](https://user-images.githubusercontent.com/52403161/69301872-9c753500-0c52-11ea-82ae-b6047d2df5ab.png)
![points+imu0](https://user-images.githubusercontent.com/52403161/69305529-478beb80-0c5f-11ea-9271-3ea6c0ae23b7.png)
I will provide my configurefiles [here](https://github.com/Fanny-one/configurefiles).
2. Besides, when I correct IMU by [the advice](https://github.com/googlecartographer/cartographer_ros/issues/902) then set rpy 0 0 -1.63 , An error appears that odom and true direction would  have 90-degree deviation. But if I set rpy 0 0 0, the deviation appear.
![1](https://user-images.githubusercontent.com/52403161/69302840-e57ab880-0c55-11ea-8323-66e8b4dbecd8.jpg)
Hope for you help, thans very much.

**Comment by dzxbiubiubiu** [comment]
Hi:)
I have met the same question that the color of the cartographer 3D map is gray.
Do you solve it?

**Comment by wjjjjyourFA** [comment]
Hi:)
I have met the same question that the color of the cartographer 3D map is gray.
when i got my lua file changed again and again, i find that white area is either the ceiling or the back of a table .
so i doubt that is there a direction of gravity or radar . but i cant test my assumption .  ..0.0..

**Comment by MichaelGrupp** [comment]
You can set the transparency (alpha) of the occupancy grid in RViz settings. Then it's white.

**Comment by Anthony1011** [comment]
hi everyone I meet the some issue, when I run the  cartographer 3D map, those surrounding objects will be detected as black grid but when I move the robot I can't get the withe zone (available area).
 
If I flip the imu then some grid turn white I'm still wondering why it is,
if any advice will appreciate.

![Screenshot from 2023-03-02 15-18-38](https://user-images.githubusercontent.com/95856492/223106840-515618a0-0da0-4c20-95b2-b2f78e900809.png)
![Screenshot from 2023-03-02 15-20-06](https://user-images.githubusercontent.com/95856492/223106888-b24f37dd-d583-4eca-a82c-54a20cccfe27.png)
