### ISSUE TITLE
Load frozen state

### ISSUE THREAD

**Issue by barzelshir** [cartographer-project/cartographer_ros#1439]
Can someone please elaborate on what it means to load a frozen state?
(I couldn't find any description of it in the documentation) 

1. If I understood correctly in terms of trimming, any of the submaps of a frozen trajectory won't be trimmed, but how does it effects the optimization problem?

2. What does it mean in the code below to set the parameter block as constant in case of a frozen trajectory, does a frozen trajectory will cause all it submaps to be frozen?

`    if (first_submap || frozen) {
      first_submap = false;
      // Fix the pose of the first submap or all submaps of a frozen
      // trajectory.
      problem.SetParameterBlockConstant(C_submaps.at(submap_id_data.id).data());
    }
`

Thanks

**Comment by MichaelGrupp** [comment]
Loading a frozen state means that no pose graph constraints are inserted. A frozen trajectory is unaffected by optimization, thus also its submaps.

Trimming (parts of) a frozen trajectory is possible, although this is not done in the currently implemented trimmers of the upstream repo.
