### ISSUE TITLE
Correct setup of lua to use odometry

### ISSUE THREAD

**Issue by francescoricciuti** [cartographer-project/cartographer_ros#1440]
Dear community,

I managed to include odometry into my mapping process, but I was wondering which is the best setup for lua/tf.

All the setup I tried are with the following urdf: [robot.txt](https://github.com/googlecartographer/cartographer_ros/files/4102076/robot.txt)

I tried the following configurations:

- 1: publishing the tf between odom and base_link and using the following lua:
`tracking_frame = "imu_link",`
` published_frame = "odom",`
` odom_frame = "odom",`
`provide_odom_frame = false,`
` publish_frame_projected_to_2d = false,`
`use_pose_extrapolator = true,`
` use_odometry = true,`

- 2: not publishing the tf between odom and base_link and using the following lua:
`tracking_frame = "imu_link",`
` published_frame = "base_link",`
` odom_frame = "odom",`
`provide_odom_frame = true,`
` publish_frame_projected_to_2d = false,`
`use_pose_extrapolator = true,`
` use_odometry = true,`

From my understanding, both are formally correct and in fact they both seem to work fine for my application, but I was wondering which is the best between the two, and why.

Thanks for your time!

Francesco

**Comment by nyangshawbin** [comment]
Hi, regarding setting of the published frame, I think this [issue](https://github.com/cartographer-project/cartographer_ros/issues/1230) could be helpful for you. Generally, the root frame of your tf tree should be set as your published frame.

Additionally, if you are looking at providing your own odom in your setup by setting your `use_odometry= true`, you need not set `provide_odom_frame= true`. Hence option 1 does seems like a better option if you are intending to use Cartographer with an externally provided odom. Similarly, this [link](https://github.com/cartographer-project/cartographer_ros/issues/300) could help in your understanding.
