### ISSUE TITLE
High memory usage with overlapping submaps trimmer -> possible solution (malloc_trim(0))

### ISSUE THREAD

**Issue by barzelshir** [cartographer-project/cartographer_ros#1441]
Hi all,
I have a problem with long term mapping using overlapping submaps trimmer.
I think that the problem is due to the reason that memory is not released from the heap.
I thought about using malloc_trim(0) -> (http://man7.org/linux/man-pages/man3/malloc_trim.3.html),
At the end of MarkSubmapAsTrimmed function.
I can see that memory is been released.
What do you think about it? Can it impair the performance?

**Comment by MichaelGrupp** [comment]
The problem is that the coverage grid approach of the trimmer algorithm is inefficient: https://github.com/googlecartographer/cartographer/issues/1523
