### ISSUE TITLE
Wired tf jump behavior

### ISSUE THREAD

**Issue by pl95** [cartographer-project/cartographer_ros#1444]
Hi, 
I have a wired tf jump behavior when I launch the mapping file. The tf of the upper body of the robot jump around when the base of the robot walking normally as the following gif shows.
Everything else work normally. Is there any way I can fix this?

![Screencast 2020-02-05 12_39_27](https://user-images.githubusercontent.com/36173023/73867627-072b1b00-4815-11ea-99cd-ca5994f7d013.gif)

1. [rosbag_validate_result](https://gist.github.com/pl95/ce5153e74fd3b8bb8e0eb2d7f249e303):  
2. [ Launch, lua configuration and URDF
](https://github.com/pl95/cartographer_issue)
3. My bag file:  [joytf.bag](https://drive.google.com/open?id=1ldsdDftrWgNhfUPbmycvMET-pMLkxiM-)
The data is record from real robot. 

Thank you so much!!

**Comment by qvntm** [comment]
You commented out robot_state_publisher? That publishes tf between robot links so probably that's the issue. And since its tf issue, its better to provide tf info as well. You can get the pdf by `rosrun tf view_frames` while running the nodes.

**Comment by mocibb** [comment]
There is not problem in the bag provided. I can run this bag with very good result.
![image](https://user-images.githubusercontent.com/18642/75409713-7e575900-5954-11ea-8a36-7abb5c0cd75e.png)

**Comment by unirlm** [comment]
how did you solve this issue?
