### ISSUE TITLE
Issues using build_octree

### ISSUE THREAD

**Issue by NiclasEvestedt** [cartographer-project/cartographer_ros#1445]
Hi,
I'm trying out cartographer for fun and started going through the demo examples to get familiar with it. I have had some issues creating the octotree for visualization using the point_cloud_viewer repo. Here are the steps I have gone through. 
 
I am currently looking at the Deutsches Museum 3D backpack demo and I downloaded the bag (b3-2016-04-05-14-14-00.bag).

I then ran roslaunch cartographer_ros offline_backpack_3d.launch bag_filenames:=${HOME}/Downloads/b3-2016-04-05-14-14-00.bag to get the .pbstream file.

I then changed assets_writer_backpack_3d.lua to include 
   {
      action = "write_ply",
      filename = "points.ply",
    },
in order to get a dense point cloud for visualization.

I followed the instructions to install the point_cload_viewer and tried to build an octree following the instructions in the readme. And then I hit the error below. I tried clipping the bag to only 20s to see if it was due to the size of this point cloud but I ran into the exact same error. 
https://github.com/googlecartographer/point_cloud_viewer

Any hints would be greatly appreciated! I would like to get the demo working before I try with our own data. 

```target/release/build_octree ~/scratch/demo_bag/b3-2016-04-05-14-14-00.bag_points.ply --output-directory ~/scratch/demo_bag/
Determining bounding box: 1245308232 / 1245308232 [======================================================================] 100.00 % 10552519.82/s Creating octree structure.
Splitting r which has 1245308232 points (12453.08x MAX_POINTS_PER_NODE).
thread 'thread 'thread 'thread '<unnamed><unnamed>' panicked at '<unnamed><unnamed>' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: Error(NodeNotFound, State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })called `Result::unwrap()` on an `Err` value: Error(NodeNotFound, State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })' panicked at '', called `Result::unwrap()` on an `Err` value: Error(NodeNotFound, State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', called `Result::unwrap()` on an `Err` value: Error(NodeNotFound, State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })src/libcore/result.rs', src/libcore/result.rs', ::src/libcore/result.rssrc/libcore/result.rs1188:1188::11885:
1188:55note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
:
5

thread 'main' panicked at 'WaitGroup explicitly poisoned!', /home/niclas/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-pool-1.0.0/src/lib.rs:457:13
```

**Comment by MichaelGrupp** [comment]
I recommend asking asking about this crash in the point_cloud_viewer repo. At least there has been some activity recently and it's more likely that someone knows about the Rust implementation there than here.
