### ISSUE TITLE
Is it possible to switch between slam and self-localization mode at runtime

### ISSUE THREAD

**Issue by maxbader** [cartographer-project/cartographer_ros#1446]
I have recorded a pbstream and I can use it to localize myself (2D).
I would like to change the parameters
```
TRAJECTORY_BUILDER.pure_localization = true
POSE_GRAPH.optimize_every_n_nodes = 20
```
at runtime to switch back to SLAM mode. 
Is this possible using ROS?

**Comment by artemiialessandrini** [comment]
If I'm not mistaken, in ROS it's usually done using [dynamic_reconfigure](wiki.ros.org/dynamic_reconfigure). Not sure how to link it with cartographer_ros though.

**Comment by shaoxiang** [comment]
@maxbader Hi, I have the same need. Have you solved it? 
I'm trying to see if I can change the Lua configuration dynamically.

**Comment by MichaelGrupp** [comment]
You can use the /start_trajectory service to start a trajectory with a different configuration. Note that this only changes the trajectory builder options, map builder / pose graph options can't be changed during runtime. Enabling / disabling trimming works though.
