### ISSUE TITLE
Configuration parameters for the datasets

### ISSUE THREAD

**Issue by Sumyer** [cartographer-project/cartographer_ros#1449]
1.  In your 2D paper, there are some 2D data sets  with ground truth  that  successfully  run  carto.  I  tried  it  but  the default parameters  didn't  perform well.  And  The offline mode needs the urdf file, how can I get it?

2.  How  can  I  tune  the  parameters  to make  carto  do  the  best? And  how  can I  judge  the  parameters  can do well?  Are there some parameters in cartographer or algorithms that can help to tune?

Thanks a lot!

**Comment by MichaelGrupp** [comment]
There is no general guideline. In the end, it's a complex SLAM system with many parameters that interplay with each other.

There is a tuning guide in the documentation that can help maybe to get started digging deeper: https://google-cartographer-ros.readthedocs.io/en/latest/tuning.html

For the parameters used in the paper: these are probably not available anymore and would require a completely different version anyway.
