### ISSUE TITLE
"ROS distro is not set"

### ISSUE THREAD

**Issue by DennisFaucher** [cartographer-project/cartographer_ros#1451]
Following instructions on this page: https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html
Ubuntu: 18.04.4
"rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y" returns the following error:
dpkg-query: no packages found matching liblua5.2-dev
dpkg-query: no packages found matching libprotobuf-dev
dpkg-query: no packages found matching libpcl-dev
dpkg-query: no packages found matching libprotoc-dev
dpkg-query: no packages found matching gfortran
dpkg-query: no packages found matching qtbase5-dev
dpkg-query: no packages found matching libgflags-dev
dpkg-query: no packages found matching libcairo2-dev
dpkg-query: no packages found matching libeigen3-dev
dpkg-query: no packages found matching libsuitesparse-dev
dpkg-query: no packages found matching google-mock
dpkg-query: no packages found matching protobuf-compiler
dpkg-query: no packages found matching libgoogle-glog-dev
dpkg-query: no packages found matching libatlas-base-dev
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies (ROS distro is not set. Make sure `ROS_DISTRO` environment variable is set, or use `--rosdistro` option to specify the distro, e.g. `--rosdistro indigo`):
cartographer_ros_msgs: Cannot locate rosdep definition for [std_msgs]
cartographer: No definition of [boost] for OS version [bionic]
cartographer_ros: Cannot locate rosdep definition for [rosunit]
cartographer_rviz: Cannot locate rosdep definition for [rviz]
ceres-solver: Cannot locate rosdep definition for [catkin]

**Comment by bochen87** [comment]
You have to replace ${ROS_DISTRO} by your actual ROS distro, in your case melodic
