### ISSUE TITLE
Cannot find cartographer_dev_pbstream_trajectories_to_rosbag

### ISSUE THREAD

**Issue by BenJamin-ad** [cartographer-project/cartographer_ros#1453]
Hi

I am trying to work with the `cartographer_dev_pbstream_trajectories_to_rosbag` node however this executable is not included as part of my install from the master branch. I have searched for the file pbstream_trajectories_to_rosbag_main.cc further to this and it isn't included as part of my installation (searching through src in my workspace).

Can someone suggest to me why I haven't been able to correctly install this file and hence explain why I am unable to use this node?

I have followed the instructions from here: [https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html](url) and recreated the same issue on another machine. I am able to successfully run 2d/3d demos.

Cheers.

**Comment by MichaelGrupp** [comment]
If you can `roslaunch` the demos after building, `rosrun cartographer_ros cartographer_dev_pbstream_trajectories_to_rosbag` should also work. Did you source the `setup.bash` of your catkin workspace as described here: http://wiki.ros.org/catkin/Tutorials/create_a_workspace

**Comment by MichaelGrupp** [comment]
I have updated the compilation instructions. Now it should work fine if you follow the instructions on a clean Ubuntu / ROS: https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html
