### ISSUE TITLE
Error when using /start_trajectory service

### ISSUE THREAD

**Issue by wuchenxi1996** [cartographer-project/cartographer_ros#1465]
I used pure localiztion mode of cartographer and I finished the last trajectory 1 with rosservice call /finish_trajectory 1. Then I wanted to start  a new trajectory by using /start_trajectory service with arguments, but the feedback I got showed: 
ERROR: transport error completing service call: unable to receive data from sender. 
    Does anyone encountes the same problem and know how to fix it?

**Comment by MichaelGrupp** [comment]
Looks like either a ROS communication problem or a crash of Cartographer, can't really tell. I don't encounter this problem with a recent version of Cartographer and we are heavily using these services.

**Comment by skywno** [comment]
I actually encountered the same problem.  It only happens when I call /start_trajectory service.
![image](https://user-images.githubusercontent.com/57262568/164706989-dd919e56-9e66-468d-b0d9-24c6aaaa0be6.png)
