### ISSUE TITLE
Too few poses

### ISSUE THREAD

**Issue by alexsimon1** [cartographer-project/cartographer_ros#1467]
Hello,

i have much fewer Poses (picture1) with cartographer  as with hector slam (picture2), even if the motion filter has the same parameter in both slams.

![image](https://user-images.githubusercontent.com/50982386/79460805-a29af200-7ff5-11ea-9a39-135427fee92e.png)

![image](https://user-images.githubusercontent.com/50982386/79460857-b3e3fe80-7ff5-11ea-8092-a70a9c9dd51c.png)

Is there a workaround for this Situation?

Thanks.

**Comment by MichaelGrupp** [comment]
Please take a look at: https://github.com/cartographer-project/cartographer_ros/issues/1374

**Comment by gaussiangit** [comment]
@MichaelGrupp I have another camera along with lidar. Number of camera images and poses/node_index should match in my case! How can I achieve that ?
