### ISSUE TITLE
Error when building cartographer:ros_log_sink.cc

### ISSUE THREAD

**Issue by FighterEVO** [cartographer-project/cartographer_ros#1487]
In function `cartographer_ros::ScopedRosLogSink::send(int, char const*, char const*, int, tm const*, char const*, unsigned long)':
ros_log_sink.cc:(.text+0x144): undefined reference to `google::LogSink::ToString[abi:cxx11](int, char const*, int, tm const*, char const*, unsigned long, int)'

I have never come across this problem in previous version. Any help would be greatly appreciated!

**Comment by FighterEVO** [comment]
I solved this problem by upgradding the version of protobuf, thanks!

**Comment by bill4u** [comment]
> I solved this problem by upgradding the version of protobuf, thanks!

would you please share your version of protobuf? I met the same problem.THX!
