### ISSUE TITLE
Integration of cartographer and version management

### ISSUE THREAD

**Issue by pmirabel** [cartographer-project/cartographer_ros#1490]
Hi,

Cartographer is integrated to my robot stack for a while now (ros-melodic).  
I can see versions in `package.xml` files of `cartographer` : 1.0.0, `cartographer-ros`:1.0.0 and `ceres-solver`:1.13.0 . Those seems to be old now : june 2018.  
I can see new commits on git repos, but no new packages containing those commits. 

1. Can someone explain to me the relation between git repo and ros package please?  
2. Can someone explain me how to get last versions of all packages to benefit from performance improvements and so ?  

Thanks a lot!

**Comment by MichaelGrupp** [comment]
We plan to make a new ROS package soon, but have no ETA yet. Until then, if you want to have the newest code, you need to compile and install from source code.
