### ISSUE TITLE
For 3d implementation, cartographer_node is getting connected to /submap_list topic. 

### ISSUE THREAD

**Issue by teetangh** [cartographer-project/cartographer_ros#1491]
![image](https://user-images.githubusercontent.com/44238657/87191827-dc3c7a00-c312-11ea-932e-b4977d19415e.png)

The above image shows the RQT node graph and TF tree of the differential drive I have constructed.It uses a Velodyne VLP16 lidar, an inertial measurement unit (IMU) and a laser scanner . 
Cartographer 2d implementation for this robot gives excellent results with everything working the way it should and properly connected RQT node graph and TF tree.

However for the 3d cartographer implementation, cartographer_node is getting connected to /submap_list topic and not producing any result on the /map or the /submap_list topic. 

![image](https://user-images.githubusercontent.com/44238657/87192011-33dae580-c313-11ea-95fb-5ac4b6a6be33.png)

Here is a link to the repository and the link to the lua config and cartogrpaher-ros launch files
https://github.com/teetangh/Qbotics-Labs-Internship/tree/master/diff_drive_gazebo/src/m2wr_cartographer

**Comment by MichaelGrupp** [comment]
> cartographer_node is getting connected to /submap_list topic and not producing any result on the /map or the /submap_list topic.

The cartographer_node only publishes a submap list, the *occupancy grid* node subscribes to it and publishes to /map.

That being said, you need to check your topic `remap` in the launch file, looks like you have a typo in the /velodyne_points topic.name.
