### ISSUE TITLE
Temporarily disable SLAM

### ISSUE THREAD

**Issue by AK-NOT** [cartographer-project/cartographer_ros#1497]
Hi. I wanted to ask if there is any way where I can set a condition to when the cartographer package does its analysis. I already have the package running and everything. 
Since my robot is not always parallel to the ground, there is some time where my lidar is also not parallel to the ground. I have the orientation of the robot so I know when the lidar is parallel or not to the ground. Is there a way where I can set a condition so that cartographer stops the analysis when it is not parallel and starts again when it becomes parallel.

I attached the config file. I am using ros-melodic.
[configfile.txt](https://github.com/cartographer-project/cartographer_ros/files/4972562/configfile.txt)

Thank you so much

**Comment by MichaelGrupp** [comment]
You can use `/finish_trajectory` and `/start_trajectory` to stop SLAM and restart it again at a new pose.
