### ISSUE TITLE
Mapping and localization mode in different robots

### ISSUE THREAD

**Issue by GeorgeKonno** [cartographer-project/cartographer_ros#1501]
We use a robot with sensor lidar, imu and odom to do mapping in a room, we got the pbstream to loaded in another robot whose sensors are a little different. Then change to pure localization mode in the new robot, but sometimes we found the localization is not very correct. The most possible reason is the distinguish in sensor's raw data, do we have any method to help improve the performance?

**Comment by MichaelGrupp** [comment]
If you're using 2D SLAM and the sensors are mounted differently, performance can degrade. Maybe the problem is less prominent when using 3D mode.
