### ISSUE TITLE
Requested submap X from trajectory Y but it does not exist

### ISSUE THREAD

**Issue by darthShana** [cartographer-project/cartographer_ros#1505]
HI 
Im trying to figure how to get localization working, im following the documentation on
https://google-cartographer-ros.readthedocs.io/en/latest/going_further.html

how every i get lots off 

`E0820 19:28:58.919713  6169 map_builder_bridge.cc:175] Requested submap 6 from trajectory 0 but it does not exist: maybe it has been trimmed.
[ERROR] [1597908538.919817917, 1597869816.582156400]: E0820 19:28:58.000000  6169 map_builder_bridge.cc:175] Requested submap 6 from trajectory 0 but it does not exist: maybe it has been trimmed.`

And im also not clear where i can i find the localised pose of the robot? perhaps its not being published due to the error

**Comment by MichaelGrupp** [comment]
This can happen if you use RViz and it tries to visualize a submap that doesn't exist anymore.

The pose of the robot is published on the `/tf` topic depending on your frame configuration.

**Comment by IqbalBintangsyah** [comment]
Hello, I also have this same problem with ROS2-Humble

What does it mean by a submap doesn't exist anymore? How do I stop it from happening?

Thank you
