### ISSUE TITLE
Build instructions are not up to date

### ISSUE THREAD

**Issue by MichaelGrupp** [cartographer-project/cartographer_ros#1531]
I tried building with a fresh, clean installation of ROS Noetic using our documentation and it's not great.

Fix the instructions such that they make sense and work.

---

Observations so far:

- [x] `install_proto3.sh`:
  - not needed on Noetic & Melodic, comes with rosdep. Potentially harmful there. Only recommend for Xenial.

- [x] Ceres:
  - installed by rosdep, no need to have it in the ws for Noetic (rosinstall). Do we need it for Xenial? --> fixed via #1532 

- [x] Abseil:
  - not mentioned
  - `install_abseil.sh` is provided by cartographer - installation to a catkin build dir would be nice, but the script uses `stow` so it can be "uninstalled" with `stow -D absl`. Should be fine if we explain what happens.
  - **todo**: mention installation of stow

- [x] this is required: https://github.com/cartographer-project/cartographer/pull/1705/ (the fix in FindGmock) ---> merged

**Comment by ludoux** [comment]
Thank you, I face a build problem on ROS Noetic by following the official guide.
`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.`

By installing the Abseil (`install_abseil.sh`) and the following cmake file change:
>this is required: cartographer-project/cartographer#1705 (the fix in FindGmock)

It works. Thank you again.

**Comment by MichaelGrupp** [comment]
done

**Comment by W-E-A** [comment]
Run "sudo apt-get install libgmock-dev" works for me.
