### ISSUE TITLE
global SLAM makes the map drift more, why??

### ISSUE THREAD

**Issue by bxc237** [cartographer-project/cartographer_ros#1548]
Hi, I try to generate a map in a 170m x 50m area. I turned off the global SLAM first by `POSE_GRAPH.optimize_every_n_nodes = 0`, and the result is ok for a system without global optimization. 
![path4276](https://user-images.githubusercontent.com/16990429/98212805-17784e00-1f7f-11eb-9687-0b7544af453c.png)
Zoom in the red area, I find that the drift is not really big for this map. 
![path4311](https://user-images.githubusercontent.com/16990429/98213476-15fb5580-1f80-11eb-9951-2f350d2d00e9.png)
Then I try to close the loop by turning on the global SLAM  `POSE_GRAPH.optimize_every_n_nodes = 80`, however, it introduces more drift.
![path4232](https://user-images.githubusercontent.com/16990429/98213642-5529a680-1f80-11eb-9309-a085b772d3ea.png)
Zoom in the same red area, the drift is obviously worse.
![path4261](https://user-images.githubusercontent.com/16990429/98213689-6c689400-1f80-11eb-9e00-baca05d0103c.png)
The loop seldom gets closed, when it happens to be closed, the map looks like this.
![Screenshot from 2020-10-30 18-25-40](https://user-images.githubusercontent.com/16990429/98213829-a043b980-1f80-11eb-91ac-efe8c1330469.png)
Why is the global SLAM makes the map drift more? These are my [lua](https://drive.google.com/file/d/1Dn7PvaJaeUI7J7W9vNIGWO6IPbmgTHld/view?usp=sharing) file (I only changed optimize_every_n_nodes when I tested the system; I only use odometry and scan data, no IMU; TF data for the robot is 100% correct) and [launch](https://drive.google.com/file/d/1SrBe8mRhzU3R9lbK5CguT6rSZLRxzM59/view?usp=sharing) file (need to change directory; need to change 'Fixed Frame' to 'map_2D_test' in RVIZ). The [bag](https://drive.google.com/file/d/1opHmssuejGTBlH_2n5cRQb2VcU6GBv4u/view?usp=sharing) file is pretty big since it was a long run. I will be really appreciated if anyone can help me solve this issue. Thanks!

**Comment by soorajanilkumar** [comment]
Hi @bxc237 

I tried your rosbag. There seems to be some kind of corruption at the end. If I filter out the last few seconds and use the config below , I get a good map with loop closure.

I used your config as a base and filtered out some parameters which I though would improve matching.

Granted I tested the rosbag using the offline mode, so you might have to tune for latency if you want online slam performance.

```
include "map_builder.lua"
include "trajectory_builder.lua"

options = {
  map_builder = MAP_BUILDER,
  trajectory_builder = TRAJECTORY_BUILDER,
  map_frame = "map_2D_test",
  tracking_frame = "base_footprint",
  published_frame = "odom_2D",
  odom_frame = "odom_2D",
  provide_odom_frame = false,
  publish_frame_projected_to_2d = false,
  use_odometry = true,
  use_nav_sat = false,
  use_landmarks = false,
  num_laser_scans = 1,
  num_multi_echo_laser_scans = 0,
  num_subdivisions_per_laser_scan = 1,
  num_point_clouds = 0,
  lookup_transform_timeout_sec = 0.2,
  submap_publish_period_sec = 0.5,
  pose_publish_period_sec = 0.5,
  trajectory_publish_period_sec = 0.5,
  rangefinder_sampling_ratio = 1.,
  odometry_sampling_ratio = 1.,
  fixed_frame_pose_sampling_ratio = 1.,
  imu_sampling_ratio = 1.,
  landmarks_sampling_ratio = 1.,
}

MAP_BUILDER.use_trajectory_builder_2d = true

TRAJECTORY_BUILDER_2D.min_range = 0.1
TRAJECTORY_BUILDER_2D.max_range = 12.
TRAJECTORY_BUILDER_2D.missing_data_ray_length = 12.
TRAJECTORY_BUILDER_2D.use_imu_data = false
TRAJECTORY_BUILDER_2D.use_online_correlative_scan_matching = true

POSE_GRAPH.optimize_every_n_nodes = 20 -- for offline mapping (might be different for online case)
TRAJECTORY_BUILDER_2D.submaps.num_range_data = 80

TRAJECTORY_BUILDER_2D.motion_filter.max_angle_radians = math.rad(1) -- 1 degree seems more apt
TRAJECTORY_BUILDER_2D.motion_filter.max_distance_meters = 0.1


POSE_GRAPH.constraint_builder.min_score = 0.6 -- increased threshold to throw away wrong matches
POSE_GRAPH.constraint_builder.global_localization_min_score = 0.4

POSE_GRAPH.constraint_builder.max_constraint_distance = 20.

-- odometry was good, so i used for atleast translation to weed out any incorrect constraints
POSE_GRAPH.optimization_problem.odometry_translation_weight = 1000
POSE_GRAPH.optimization_problem.odometry_rotation_weight = 10

-- increased search radius
POSE_GRAPH.constraint_builder.fast_correlative_scan_matcher.linear_search_window = 15

return options

```

Main changes
- increased search radius
- increased motion filter from 0.1 degrees to 1 degree for latency
- increased min score to weed out incorrect matches

I am by no means an expert and there might be other things which can be improved. @MichaelGrupp  can advice on further modifications. 

Cheers

**Comment by bxc237** [comment]
Hi @soorajanilkumar ,
Thank you for your awesome advice! Soon after I posted this issue, we found the solution so that I forgot to close this issue. You are right, the key points are "increase min score to weed out incorrect matches" and "increase POSE_GRAPH.optimize_every_n_nodes to 20~30".
