### ISSUE TITLE
ImportError: No module named catkin.builder;why??????

### ISSUE THREAD

**Issue by ngadminq** [cartographer-project/cartographer_ros#1554]
I'm trying to install cartographer_ros package in the environment of Ubuntu 18.04 and ROS Melodic;

why??????
when I run `../catkin_make_isolated --install` ,I got a error.
root@one-desktop:/opt/ros/melodic/bin/catkin_ws# ../catkin_make_isolated --install
Traceback (most recent call last):
  File "../catkin_make_isolated", line 13, in <module>
    from catkin.builder import apply_platform_specific_defaults  # noqa: E402
ImportError: No module named catkin.builder

**Comment by MichaelGrupp** [comment]
This looks like catkin problem that is unrelated to Cartographer itself. Please consult the ROS forum and catkin issue tracker for this, e.g. https://answers.ros.org/question/347793/no-module-named-catkinbuilder/
