### ISSUE TITLE
Cartographer output cannot allign frames.

### ISSUE THREAD

**Issue by trevgilk** [cartographer-project/cartographer_ros#1560]
Hi,

We tried cartographer with a handheld single velodyne 32c and an IMU. Unless there's very little movement or the lidar is static the slam is very messy and appears to be a disorganized “blob,” as can be seen in the attached image. We think there could be an issue in the .urdf file and We're trying to update the values to reflect our setup. We are wondering if anything in the .launch file or .lua file isn't setup properly.

[Bag file](https://drive.google.com/file/d/1vYYBhSPaNGl6L2gOfNxGHSHDm-e4FCAz/view)

[.urdf file](https://github.com/trevgilk/cartographer_ros/blob/master/cartographer_ros/urdf/ingenium_lidar_stick.urdf)

[slam.launch file](https://github.com/trevgilk/cartographer_ros/blob/master/cartographer_ros/launch/ingenium_slam.launch)

[slam.lua file](https://github.com/trevgilk/cartographer_ros/blob/master/cartographer_ros/configuration_files/ingenium_slam.lua)

These are the files we used to generate the point cloud and images:
[localization.launch file](https://github.com/trevgilk/cartographer_ros/blob/master/cartographer_ros/launch/ingenium_localization.launch)

[localization.lua](https://github.com/trevgilk/cartographer_ros/blob/master/cartographer_ros/configuration_files/ingenium_localization.lua)

[Here ](https://github.com/JohannesByle/ingenium_cartographer)is the repository we used to work on the .launch files and .urdf files

Pictures:
Static:
![2020-11-09-22-50-05 bag_xray_xz_all_color](https://user-images.githubusercontent.com/74393194/99134188-4d05e280-25e2-11eb-9b43-4a907d83ae79.png)

With movement:
![2020-11-11-20-50-43 bag_xray_xy_all_color](https://user-images.githubusercontent.com/74393194/99134220-6f97fb80-25e2-11eb-8ac7-5ec7faace3f6.png)

**Comment by eithwa** [comment]
![螢幕擷取畫面 2021-08-19 113257](https://user-images.githubusercontent.com/26001028/130005231-e7d22276-8705-4134-9cdf-e1feb1fc0f26.png)
I modified urdf and lua to make it work slightly
[ingenium.zip](https://github.com/cartographer-project/cartographer_ros/files/7011577/ingenium.zip)

**Comment by JohannesByle** [comment]
Thank you for answering! We ended up fixing the problem a while ago, the problem ended up being with the urdf, we had the imu pointed upside down and the lidar not rotated properly. @trevgilk I suggest closing this issue.
