### ISSUE TITLE
Not able to localize - need help with tuning

### ISSUE THREAD

**Issue by francescoricciuti** [cartographer-project/cartographer_ros#1571]
Hi everybody.

I'm not able to localize on a map, neither live nor with a bag. Note that the bag I'm attaching here is the one I used to build the map.

[Here](https://gist.github.com/francescoricciuti/5ea5a34c5d4c0cc791b3e0fca5d50b8e.js) the output of rosbag validate
[Here](https://www.dropbox.com/s/75qd1i7dte7vq5m/localization.zip?dl=0) the bag.
[Here](https://github.com/cartographer-project/cartographer_ros/files/5622400/mapping.txt) the Lua used to build the map
[Here](https://github.com/cartographer-project/cartographer_ros/files/5622417/mapping_launch.txt) the launch file to build the map
[Here](https://github.com/cartographer-project/cartographer_ros/files/5622423/localization.txt) the Lua I usually use with this setup for localization, that already worked well in many other cases with maps with similar extension
[Here](https://github.com/cartographer-project/cartographer_ros/files/5622435/localization_launch.txt) the launch file I use to localize

The tfs are already in the bag file.

Can someone help me out with this?

Thanks a lot

**Comment by johuber** [comment]
Unfortunately we do not have the capacity to support you with tuning.

Please refer to the tuning guide [here](https://google-cartographer-ros.readthedocs.io/en/latest/tuning.html).

Additional advice I can give to you is to make sure, that all your sensor data is sane and in the required format.
