### ISSUE TITLE
Ros2 Foxy Installation Fails

### ISSUE THREAD

**Issue by seasony-vp** [cartographer-project/cartographer_ros#1579]
Installing cartographer_ros for [ros2 foxy](https://index.ros.org/p/cartographer/github-ros2-cartographer/#foxy) does not work.

The failure happens at this step from the [docs](https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html#building-installation)
`rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y
`

The error message:
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
cartographer_rviz: Cannot locate rosdep definition for [rviz]
cartographer_ros_msgs: Cannot locate rosdep definition for [message_runtime]
cartographer_ros: Cannot locate rosdep definition for [rosunit]
```
My hunch is that the [rosunit](https://index.ros.org/p/rosunit/), [message_runtime](https://index.ros.org/p/message_runtime/) and [rviz](https://index.ros.org/r/rviz/#foxy) packages haven't been released for foxy and "rviz" has now been updated  to "rviz2".

For clarity, would I be correct in assuming that cartographer_ros has not yet been ported to foxy? 

EDIT: After some further digging it seems that merge #1543 would fix this issue?

**Comment by seasony-vp** [comment]
Solved. To install with foxy use the downstream repo at ros2/cartographer.

Install by running this command: `sudo apt-get install ros-foxy-cartographer` as referenced [here](https://github.com/ros2/cartographer/issues/19#issuecomment-654301213).

**Comment by MichaelGrupp** [comment]
The branch is currently in development. Sorry for the inconvenience.
