### ISSUE TITLE
Switch Operation Mode during runtime

### ISSUE THREAD

**Issue by Tristan9497** [cartographer-project/cartographer_ros#1586]
Hi,
is it possible to switch the operation mode of cartographer during runtime (from SLAM to localization only)?
I am using it to Map a road-like environment and want to switch to localization only after the robot has completed its first loop to minimize the computation cost.

Thanks in advance
Tristan

**Comment by johuber** [comment]
You cannot change any parameters during run-time so you cannot change mode.

You'll probably want to export the pbstream and then restart cartographer in pure localization mode. In pure localization mode you probably want to use a different parameter set for optimal performance.

**Comment by Tristan9497** [comment]
Thanks for the quick answer!
I'll take a look at that. It unfortunate that i cant change the mode, because i guess during restart of cartographer every tf transform will be dropped which in return will generate a lot of exceptions.
