### ISSUE TITLE
How to edit map data?

### ISSUE THREAD

**Issue by makeitjune** [cartographer-project/cartographer_ros#1643]
Hi,
I'm beginner using cartographer.
I made a map file(.pgm) from pbstream file.
![map_capture](https://user-images.githubusercontent.com/83045205/121308734-58cd4380-c93c-11eb-859a-2b078e59c1eb.png)

After that,I ran pure localization and it works.
So, i want to modify a map using external tool(gimp or some image edit tool) to add or remove data(obstacles, walls etc).

But if i edit .pgm file, how can i apply change thing to .pbstream?
As far as i know, cartographer save all SLAM data(trajectory, submap, pose_graph etc) to  .pbstream file.
Running pure_localization, I should load a .pbstream file. 

If i want to edit map data what i have to do?
Thank you.

**Comment by johuber** [comment]
The pgm file is just there for visualization purposes and it is not possible to change the pbstream by editing the pgm file.
Developing a tool to edit map data would be a significant effort and there is no trivial way of doing it.

One "simpler" approach if you need to filter some obstacles and walls is already filtering the corresponding points in the original point cloud that you use to build the map.

**Comment by makeitjune** [comment]
> The pgm file is just there for visualization purposes and it is not possible to change the pbstream by editing the pgm file.
> Developing a tool to edit map data would be a significant effort and there is no trivial way of doing it.
> 
> One "simpler" approach if you need to filter some obstacles and walls is already filtering the corresponding points in the original point cloud that you use to build the map.



> The pgm file is just there for visualization purposes and it is not possible to change the pbstream by editing the pgm file.
> Developing a tool to edit map data would be a significant effort and there is no trivial way of doing it.
> 
> One "simpler" approach if you need to filter some obstacles and walls is already filtering the corresponding points in the original point cloud that you use to build the map.

Thank you

**Comment by MigVega** [comment]
As you mentioned [makeitjune](https://github.com/makeitjune), you will need the original `.pbtream` map to use cartographer in pure localization mode.
I understand the need to edit the map and that doing it on `.pgm` is easier.

Besides what [johuber](https://github.com/johuber) suggested, you can also convert your  `.pgm`  again to `.pbtream` with the [Ogm2Pgbm package](https://github.com/MigVega/Ogm2Pgbm/tree/main/ogm2pgbm).

Additionally, if you wanna run the tool in a separate docker container, you can follow the instructions in the [readme](https://github.com/MigVega/Ogm2Pgbm).

Have fun, and enjoy the power of graph-based localization! :D
