### ISSUE TITLE
Build cartographer_ros error

### ISSUE THREAD

**Issue by dongtranthien** [cartographer-project/cartographer_ros#1663]
Hi all, 
I cloned the repository(master branch) and built on the catkin workspace but the error comes up:

cartographer_ros/cartographer_ros/cartographer_ros/ros_map_writing_points_processor.h:25:10: fatal error: cartographer/mapping/proto/probability_grid_range_data_inserter_options_2d.pb.h: No such file or directory

However i can build repository at branch release-1.0
Please help me

![Screenshot from 2021-07-29 09-43-04](https://user-images.githubusercontent.com/11634454/127423536-6231fb7c-94d6-41be-a5dd-42cef47bd82b.jpg)

**Comment by duffrea** [comment]
I have the same problem, how do you solve it?
