### ISSUE TITLE
No tf transform between map and my own odom

### ISSUE THREAD

**Issue by Rikyuugo** [cartographer-project/cartographer_ros#1694]
Hi, I am a new to cartographer and i have read different issues but still can't determine what caused it.
I am using ros-melodic and install the cartographer by sudo apt-get install ros-melodic-carotgrapher_ros.
And i have a 3D lidar ,imu on a real robot.
Now,I wrote the odometer file and broadcast the TF tree between base_link and odom.The frame_id of my lidar is laser_link,the frame_id of my imu is imu_link,and odom's frame_id is odom.
I modified the demo_ backpack_ 3d.launch,backpack_3d.launch and backpack_3d.lua as shown below.
[issue.zip](https://github.com/cartographer-project/cartographer_ros/files/7564269/issue.zip)
This is my tf_tree.
![20211119000235](https://user-images.githubusercontent.com/70528368/142452255-6eb1f1ab-ba06-4120-8471-e8cf4d2726e7.jpg)
After rosrun tf static_tf_tranform 0 0 0 0 0 0 world map 100
![20211119000446](https://user-images.githubusercontent.com/70528368/142452283-3a54bb8a-7f4d-4535-9aa0-59787f49fe1f.jpg)

At the same time ,when i roslaunch demo_backpack_3d.launch ,it seems to have a variety of situations.
A situation
![20211119000502](https://user-images.githubusercontent.com/70528368/142454399-ae361e51-250c-4db5-97df-2238c68970ee.jpg)
Another situation（According to the current configuration, this situation occurs most）
![20211119000513](https://user-images.githubusercontent.com/70528368/142454406-5d3a09a6-8449-4fa3-8b4d-87079a1f921b.jpg)
Rviz shows this，and /scan_mached_point （I don't know what this is, and I don't seem to have posted this topic）shows the radar, but it seems only once，of course, there is no tf between map and Odom
![20211119000523](https://user-images.githubusercontent.com/70528368/142454413-9f337117-4595-4539-9071-ebb2e3db8c92.jpg)

I also tried to set provide_odom_frame = true  ,  use_odometry = false,instead of using my own odom,but there was still no transform(also there is no tf between base_link and odom)
What caused my problem, parameters or something？Or is there any way to build maps only by relying on lidar？Thanks a lot.

**Comment by eithwa** [comment]
Can you record a bag file to provide testing?

**Comment by Rikyuugo** [comment]
> can you record a bag file to provide testing? and the zip file you provided is missing the file "backpack_3d.launch"

I use rosbag rocord -a and rocord about 30s.I'm not sure if it meets your needs. If you have any questions, please continue to contact me
[https://github.com/Rikyuugo/issuebag.git](url)

**Comment by eithwa** [comment]
![image](https://user-images.githubusercontent.com/26001028/142560456-4603439a-1b4c-4dbf-84e0-6a1c9a1bfc3e.png)
File cannot be opened

**Comment by eithwa** [comment]
imu topic does not look good, I think you need to confirm your hardware
![image](https://user-images.githubusercontent.com/26001028/142569123-21d60c0e-0b83-46d8-b2a7-e731ae7c96b4.png)

**Comment by Rikyuugo** [comment]
> imu topic does not look good ![image](https://user-images.githubusercontent.com/26001028/142569123-21d60c0e-0b83-46d8-b2a7-e731ae7c96b4.png)
> 
> It should look like this under normal conditions. ![image](https://user-images.githubusercontent.com/26001028/142569885-b0933b03-f163-464b-a0db-a542646c2d50.png)
> 
> I use 2d slam and disable imu data, the map looks good ![image](https://user-images.githubusercontent.com/26001028/142569722-4113e4df-5e21-46fa-8cdd-9d0ebfd06b77.png)

Thanks a lot.I will try to build 2D map and confirm IMU. Can you share your configuration？

**Comment by Rikyuugo** [comment]
> imu topic does not look good ![image](https://user-images.githubusercontent.com/26001028/142569123-21d60c0e-0b83-46d8-b2a7-e731ae7c96b4.png)
> 
> It should look like this under normal conditions. ![image](https://user-images.githubusercontent.com/26001028/142569885-b0933b03-f163-464b-a0db-a542646c2d50.png)
> 
> I use 2d slam and disable imu data, the map looks good ![image](https://user-images.githubusercontent.com/26001028/142569722-4113e4df-5e21-46fa-8cdd-9d0ebfd06b77.png)

I tried 2D mapping and succeeded.It seems that it is indeed the problem of IMU. Thank you very much.close
