### ISSUE TITLE
Failed to open proto stream [Assets writer]

### ISSUE THREAD

**Issue by selvavignesh-2206** [cartographer-project/cartographer_ros#1725]
I am trying to launch the assets writer with my bag and pbstream. However, the process dies. The error that pops up is "failed to open proto stream". I am not sure how to resolve this. The error details are as follows:

![image](https://user-images.githubusercontent.com/67449946/175907434-0ebb1ecf-1f83-4b30-a87e-971abdd735f9.png)

> REQUIRED process [cartographer_assets_writer-2] has died!
> process has died [pid 60048, exit code -6, cmd /home/caato2/cartographer_ws/install_isolated/lib/cartographer_ros/cartographer_assets_writer -configuration_directory /home/caato2/cartographer_ws/install_isolated/share/cartographer_ros/configuration_files -configuration_basename assets_writer_backpack_3d.lua -urdf_filename /home/caato2/cartographer_ws/install_isolated/share/cartographer_ros/urdf/backpack_3d.urdf -bag_filenames mbclv10.bag -pose_graph_filename mbclv10.bag.pbstream __name:=cartographer_assets_writer __log:=/home/caato2/.ros/log/c7007f44-f5f9-11ec-869d-f712ba5de956/cartographer_assets_writer-2.log].
> log file: /home/caato2/.ros/log/c7007f44-f5f9-11ec-869d-f712ba5de956/cartographer_assets_writer-2*.log
> Initiating shutdown!

Thanks so much.

**Comment by cjchang925** [comment]
Try to use absolute path(like '${HOME}/path/to/the/pbstream')

**Comment by selvavignesh-2206** [comment]
Yes that was the issue. Managed to solved it. Thanks
