### ISSUE TITLE
How does cartographer work with TUM RGB-D SLAM Dataset 

### ISSUE THREAD

**Issue by zhehangT** [cartographer-project/cartographer_ros#318]
# Overview
Thank you for excellent job.

I am very interested at how's cartographer going to perform on TUM RGB-D SLAM Dataset .
But I failed to get any map when I run cartographer and TUM RGB-D SLAM Dataset rosbag file.
It seems something wrong with the TF Transformation, but I am not sure.

1.You can find all the required launch and configuration files on my fork under the "tum" branch.
https://github.com/zhehangT/cartographer_ros/tree/tum
1.The rosbag file is rgbd_dataset_freiburg2_pioneer_slam2.bag from
http://vision.in.tum.de/data/datasets/rgbddataset/download#freiburg2_pioneer_slam2
http://vision.in.tum.de/rgbd/dataset/freiburg2/rgbd_dataset_freiburg2_pioneer_slam.bag

# Run Step with Laser Data
The bag file rgbd_dataset_freiburg2_pioneer_slam2.bag contains laser data. At first I use laser data to build map.

launch cartographer
`roslaunch cartographer_ros tum_laser.launch`

launch bag file to publish data
`roslaunch cartographer_ros tum_laser_data.launch`

Cartographer can not build the map and seem to get stuck.

![image](https://cloud.githubusercontent.com/assets/8287252/25553199/70e8e198-2cdf-11e7-91c7-3d9215bd6bbd.png)

But when publish laser data 30 seconds delay. Cartographer can build map. I don't know  why does it work.
launch cartographer
`roslaunch cartographer_ros tum_laser.launch`

launch bag file to publish data
`roslaunch cartographer_ros tum_laser_data_s30.launch`
![image](https://cloud.githubusercontent.com/assets/8287252/25553203/826959f2-2cdf-11e7-9527-7fd744a7a054.png)

# Run Step with RGBD Data

My main purpose is to build map with rgbd data. So I get rgbd laser data from rgbd_dataset_freiburg2_pioneer_slam2.bag using depthimage_to_laserscan package. And I give the same  frame of rgbd laser data as laser data. 

launch cartographer
`roslaunch cartographer_ros tum_rgbd.launch`

launch bag file to publish data
`roslaunch cartographer_ros tum_rgbd_data.launch`

Cartographer can not build the map sadly.
![image](https://cloud.githubusercontent.com/assets/8287252/25553211/ad6f0cd2-2cdf-11e7-8952-bd1adb059bb8.png)

# Help
How can I build a correct map from TUM RBGD Dataset? I am very confused on how to write my lua file. 
Looking forward to your favourable reply.
Best Regards.

**Comment by SirVer** [comment]
I am sorry, I will not be able to look into this for the next 2 months. I am very interested how Cartographer performans and expect that it should work well.

**Comment by janboeye** [comment]
I made following changes and try to start it, 
diff --git a/cartographer_ros/configuration_files/tum_rgbd.lua b/cartographer_ros/configuration_files/tum_rgbd.lua
index f12945f..22da09e 100644
--- a/cartographer_ros/configuration_files/tum_rgbd.lua
+++ b/cartographer_ros/configuration_files/tum_rgbd.lua
@@ -13,9 +13,11 @@
 -- limitations under the License.
 
 include "map_builder.lua"
+include "trajectory_builder.lua"
 
 options = {
   map_builder = MAP_BUILDER,
+  trajectory_builder =  TRAJECTORY_BUILDER,
   map_frame = "map",
   tracking_frame = "laser",
   published_frame = "odom",
@@ -23,11 +25,14 @@ options = {
   provide_odom_frame = false,
   use_odometry = true,
   use_laser_scan = true,
-  use_multi_echo_laser_scan = false,
+  num_laser_scans = 1,
+  num_multi_echo_laser_scans = 0,
+  num_subdivisions_per_laser_scan = 0,
   num_point_clouds = 0,
   lookup_transform_timeout_sec = 0.2,
   submap_publish_period_sec = 0.3,
   pose_publish_period_sec = 5e-3,
+  trajectory_publish_period_se = 30e-3,
 }
 
 MAP_BUILDER.use_trajectory_builder_2d = true

But it reports laser_min_range was used the wrong number of times and then crash.

**Comment by janboeye** [comment]
I changed tum_rgbd.lua as following, then I could start it, but get same result as what you get. 
include "map_builder.lua"
include "trajectory_builder.lua"

options = {
  map_builder = MAP_BUILDER,
  trajectory_builder =  TRAJECTORY_BUILDER,
  map_frame = "map",
  tracking_frame = "laser",
  published_frame = "odom",
  odom_frame = "odom",
  provide_odom_frame = false,
  use_odometry = true,
  num_laser_scans = 1,
  num_multi_echo_laser_scans = 0,
  num_subdivisions_per_laser_scan = 1,
  num_point_clouds = 0,
  lookup_transform_timeout_sec = 0.2,
  submap_publish_period_sec = 0.3,
  pose_publish_period_sec = 5e-3,
  trajectory_publish_period_sec = 30e-3,
}

MAP_BUILDER.use_trajectory_builder_2d = true

TRAJECTORY_BUILDER_2D.min_range = 0.1
TRAJECTORY_BUILDER_2D.max_range = 4.0
TRAJECTORY_BUILDER_2D.use_imu_data = false
TRAJECTORY_BUILDER_2D.motion_filter.max_time_seconds = 0.3
TRAJECTORY_BUILDER_2D.motion_filter.max_distance_meters = 0.2
TRAJECTORY_BUILDER_2D.motion_filter.max_angle_radians = math.rad(3.)
TRAJECTORY_BUILDER_2D.ceres_scan_matcher.translation_weight = 70
TRAJECTORY_BUILDER_2D.ceres_scan_matcher.rotation_weight = 300

TRAJECTORY_BUILDER_2D.submaps.resolution = 0.035
TRAJECTORY_BUILDER_2D.submaps.num_range_data = 120
SPARSE_POSE_GRAPH.optimize_every_n_scans = 120
SPARSE_POSE_GRAPH.constraint_builder.min_score = 0.82
SPARSE_POSE_GRAPH.constraint_builder.sampling_ratio = 1.

return options

**Comment by janboeye** [comment]
it looks like that it is because the bag file's depth image is 32fc1 format, but depthimage_to_laserscan does not support this. @zhehangT

**Comment by bochen87** [comment]
closing, as inactive for a long time
