### ISSUE TITLE
Provide a .clang-format-file in the repository to ease consistent formatting

### ISSUE THREAD

**Issue by cwecht** [cartographer-project/cartographer_ros#781]
With a .clang-format-file in the repository, consistent formatting would be much easier to archive.

**Comment by ojura** [comment]
Agreed, `-style=google` differs across clang-format versions.

**Comment by cwecht** [comment]
Even if this project is using basically one of the build-in styles, an .clang-format-file would make it easier, because you do not need to reconfigure your IDE for every project, but you just can say: "use the .clang-format-file in the repo".

**Comment by MichaelGrupp** [comment]
Fixed!
