### ISSUE TITLE
Recommended sensors

### ISSUE THREAD

**Issue by alexsmartens** [cartographer-project/cartographer_ros#796]
Hi there,
would you recommend any specific sensors to be used with cartographer?
Thanks in advance

**Comment by kentsommer** [comment]
Cartographer works with a wide array of sensors and the difference in cost can be enormous. So, it is difficult to recommend anything specific. 

The 3D backpack setup (which is well tested) used two Velodyne VLP-16's and a Microstrain 3DM-GX5-25.

**Comment by Entropy512** [comment]
@kentsommer Do you happen to know which of the numerous seemingly similar Microstrain ROS nodes were used with the 3DM-GX4-25?  There seem to be at least 3 possible options for Microstrain IMUs.

**Comment by bochen87** [comment]
closing, as inactive for a long time
