### ISSUE TITLE
How to configure 3D lidar to implement cartographer?

### ISSUE THREAD

**Issue by wxt-github** [cartographer-project/cartographer_ros#842]
Hello everyone!
   I have a turtlebot cart and a 3D 16-line laser radar. I want to implement the cartographer 3D construction, but I don't know how to modify my backpack_3d.urdf、backpack_3d.lua、demo_3d.rviz and backpack_3d.launch files.If anyone can help, it would be greatly appreciated.

**Comment by gaschler** [comment]
Please find a similar answer in https://github.com/googlecartographer/cartographer_ros/issues/828#issuecomment-381888864 and see the tuning guide.

**Comment by bochen87** [comment]
closing, as inactive for a long time
