### ISSUE TITLE
Pure Localisation -  Using Cartographer to perform localisation from point cloud data

### ISSUE THREAD

**Issue by ekow-mensah** [cartographer-project/cartographer_ros#852]
Hi, This is more of a question rather than an issue and I really need some help.  Is it possible to perform localisation only with Google Cartographer while an external program displays a map of the environment? Velodyne has a ROS package which displays a 3D point cloud of the environment. Could I use that as the map and then use cartographer_ros to perform localisation?

**Comment by gaschler** [comment]
As long as cartographer_ros can subscribe to the topic of PointCloud2 messages, there are no limitations.

> Could I use that as the map and then use cartographer_ros to perform localisation?

Not sure what you mean. Cartographer can only localize on maps it made itself (there may be work-arounds in 2D).

**Comment by ekow-mensah** [comment]
oh okay could you please explain the possible work-arounds?

**Comment by ojura** [comment]
This an often requested feature. However, it's not trivial, and unfortunately not implemented (yet).
E.g. https://github.com/googlecartographer/cartographer_ros/issues/706#issuecomment-364882438

**Comment by ekow-mensah** [comment]
Okay yes i'd imagine it will not be trivial to implement

**Comment by eugenfunk** [comment]
It's trivial. :) Build the map as gazebo model, drive around with cartographer and save it. :))

**Comment by bochen87** [comment]
closing, as inactive for a long time
