### ISSUE TITLE
Use trajectory_node_list_publisher as a latchted publisher

### ISSUE THREAD

**Issue by fnobis** [cartographer-project/cartographer_ros#855]
When the cartographer ros node is run, I want to save the map and the trajectory it generates. However, when the carographer is finished, I cant read out the "trajectory_node_list" topic anymore. I therefore changed the publisher to: latch = true in the node.cc file. My suggestion would be to use this in the standard version as well. 

Additionally I encounter the problem that the occupancy grid node sometimes does not publish the map topic anymore. This is despite the fact, that the topic is latched in the node. This seems random to me. Sometimes it published a map sometimes it doesnt. Maybe someone on here has more insights.
Thanks.

**Comment by alankdkd** [comment]
I also want to get the trajectory node list after global SLAM has corrected the trajectory.  Has this change been made to the standard version?  Or do I have to make the change and recompile?  Thanks!  Alan

**Comment by MichaelGrupp** [comment]
The topics you mention are not suitable for this. You should write a pbstream file and use `cartographer_pbstream_to_ros_map` and `cartographer_dev_pbstream_trajectories_to_rosbag` to extract the data to ROS.
