### ISSUE TITLE
Loop Closing

### ISSUE THREAD

**Issue by gullermo** [cartographer-project/cartographer_ros#857]
Hello,

I have a question regarding the loop closing.
Are there any specific parameters that I have to tune to get a loop closure?
I have been working with the google cartographer and the system is working reasonably fine. Now I will make some larger trials with the robot, trying to get loop closure.
Any advice/help to get this working would be appreciated.

Thanks in advance!

**Comment by gaschler** [comment]
https://google-cartographer-ros.readthedocs.io/en/latest/tuning.html

Please describe your issue more precisely. Share the output of cartographer_rosbag_validate, show your entire configuration, ideally in a forked repo so we can see the difference to the default parameters.

**Comment by bochen87** [comment]
closing, as inactive for a long time
