### ISSUE TITLE
RealTime Loop Closure Detection Possible and Auto Localisation?

### ISSUE THREAD

**Issue by CycleMark** [cartographer-project/cartographer_ros#862]
Hi,

I've used cartographer a couple of times to build a map manually (using 2D Lidar) and it's working very well

Couple of things I would like to know

1) Is it possible to determine closed loop detection (from a topic or other) in real time. So that I can build a ros process to autonomously map an environment can know when to complete? And if so how?

Similar question to this I guess - but I couldn't see how the answer would work in my case

https://github.com/googlecartographer/cartographer_ros/issues/857

2) At the moment I am using the standard ROS AMCL process to navigate the environment and localise. Is it possible to do this in cartographer instead? That is build and save a map with cartographer then reload the map (into cartographer) and have it figure out from the sensor readings where the robot is in the known environment? Again, if possible, any pointers on how to achieve this would be great.

Many Thanks

Mark

**Comment by gaschler** [comment]
Both is possible and many users have done this.

> Is it possible to determine closed loop detection (from a topic or other) in real time

Cartographer does loop constraint search and optimization all the time in the background.
Just make sure the background threads can keep up.
The default parameters assume a high-end machine, if your device is less powerful, tune for low latency.
2D is very easy to tune for real time performance.

>  autonomously map an environment can know when to complete

Just to make sure, Cartographer does the mapping, but it does not control where to drive.

> localise. 

Cartographer_ros publishes the `tf` topic with frame `base_link`, which is the current localization. (Please see the documentation.)

>  That is build and save a map with cartographer then reload the map (into cartographer) 

Use the pbstream that is output. Start `cartographer_node` with argument `-load_state_filename YOURMAP.pbstream`. Please see the documentation on "pure localization" which is related.

> have it figure out from the sensor readings where the robot is in the known environment? 

Currently, this is not straightforward. The only way would be to use `PoseGraphInterface::constraints()` and make sure that a constraint between a recent part of your trajectory and that of the map was found. cartographer_node does not check for this, but you can take a look at the constraint visualization in `MapBuilderBridge::GetTrajectoryNodeList` which finds `last_inter_trajectory_constrained_node`.

**Comment by CycleMark** [comment]
Hi gascgler,

Many thanks for the reply. very useful info. Can you point me in the direction of the doc/info that will tell me what I need to monitor to determine loop closure? I understand that the algo itself doesn't drive the robot.

Thanks

Mark

**Comment by bochen87** [comment]
closing, as inactive for a long time
