### ISSUE TITLE
cartographer_ros build error "could not find a package configuration file provided by "tf2_eigen""

### ISSUE THREAD

**Issue by xielingsen** [cartographer-project/cartographer_ros#878]
I followed the [instructions](https://google-cartographer-ros.readthedocs.io/en/latest/) but have problems:
......
_CMake Warning at /home/tmp/ros/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "tf2_eigen" with
  any of the following names:

    tf2_eigenConfig.cmake
    tf2_eigen-config.cmake

  Add the installation prefix of "tf2_eigen" to CMAKE_PREFIX_PATH or set
  "tf2_eigen_DIR" to a directory containing one of the above files.  If
  "tf2_eigen" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:45 (find_package)

-- Could not find the required component 'tf2_eigen'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /home/tmp/ros/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "tf2_eigen" with
  any of the following names:

    tf2_eigenConfig.cmake
    tf2_eigen-config.cmake

  Add the installation prefix of "tf2_eigen" to CMAKE_PREFIX_PATH or set
  "tf2_eigen_DIR" to a directory containing one of the above files.  If
  "tf2_eigen" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:45 (find_package)

-- Configuring incomplete, errors occurred!
See also "/apollo/modules/slam/catkin_ws/build_isolated/cartographer_ros/CMakeFiles/CMakeOutput.log".
See also "/apollo/modules/slam/catkin_ws/build_isolated/cartographer_ros/CMakeFiles/CMakeError.log".
<== Failed to process package 'cartographer_ros': 
  Command '['/apollo/modules/slam/catkin_ws/install_isolated/env.sh', 'cmake', '/apollo/modules/slam/catkin_ws/src/cartographer_ros/cartographer_ros', '-DCATKIN_DEVEL_PREFIX=/apollo/modules/slam/catkin_ws/devel_isolated/cartographer_ros', '-DCMAKE_INSTALL_PREFIX=/apollo/modules/slam/catkin_ws/install_isolated', '-G', 'Ninja']' returned non-zero exit status 1_
......

System config:
gcc version 4.8.5 (Ubuntu 4.8.5-2 ubuntu1~14.04.1) 
ROS Indigo

Any help would be appreciated.Thanks!

**Comment by MichaelGrupp** [comment]
`sudo apt install ros-indigo-tf2-eigen`

This might also be useful for you: https://github.com/googlecartographer/cartographer_ros/blob/master/scripts/install_debs.sh
