### ISSUE TITLE
cartographer newbie - how to setup

### ISSUE THREAD

**Issue by dmaugis** [cartographer-project/cartographer_ros#936]
I would like to do a realtime 2D SLAM with cartographer - I have already setup ros, catkin on a raspberry pi3 (just a test, not for production). I have an ibeo scala lidar attached (4 layers). I can see a PointCloud2 on rviz already so it's somehow working. My launch file is:
`<launch>
<node name="rviz" pkg="rviz" type="rviz" args="" />
<node name=tf"      pkg="tf2_ros" type="static_transform_pulisher" args="0 0 0 0 0 0 map ibeo_scala" />
<node name="ibeo_scala" pkg="ibeo_scala" type="ibeo_scala" />
</launch>`
Then I installed:
`sudo apt-get install ros-kinetic-cartographer ros-kinetic-cartographer-ros ros-kinetic-cartographer-ros-msgs ros-kinetic-cartographer-rviz`
But I am at a loss on how to setup afterward... I tried:
`rosrun cartographer_ros cartographer_node`
but it crashed (-configuration_directory is missing)

Could someone point me on a good explanation on how to setup this ? I m not even sure if I m missing something or not.

Thanks a lot !

**Comment by FlorentRevest** [comment]
Check [the .launch files provided by cartographer_ros](https://github.com/googlecartographer/cartographer_ros/tree/master/cartographer_ros/launch) for good examples of how to run cartographer_ros.
The cartographer_node expects [several mandatory arguments](https://github.com/googlecartographer/cartographer_ros/blob/master/cartographer_ros/launch/backpack_2d.launch#L24) to point at your configuration directory and file. Again, you'll be able to find [plenty of examples](https://github.com/googlecartographer/cartographer_ros/tree/master/cartographer_ros/configuration_files).
