### ISSUE TITLE
How to use 2 Lidar and 1 IMU in Cartographer

### ISSUE THREAD

**Issue by pangchenglin** [cartographer-project/cartographer_ros#948]
In my project, I want to  achieve offroad navigation on our robotics .
And I hope use 2 Lidar and 1 IMU to do  the thing like Demo:offline_backpack_3d .I haven't find suitable drive for 2 Velodyne VLP-16. Should I write a drive for 2 Velodyne VLP-16？ Or can you provide it to me?And how to achieve this program?Please tell me .
                                                                                                                                                 Many Thanks.

**Comment by FlorentRevest** [comment]
Using Cartographer with 2 VLP16 and 1 IMU is possible.
You just need to configure your ``.launch`` file with the right options. For instance, make sure you have set ``num_point_clouds = 2`` like in [backpack_3d.lua](https://github.com/googlecartographer/cartographer_ros/blob/master/cartographer_ros/configuration_files/backpack_3d.lua#L34) and remapped your VLP topics to points2_1 and points2_2 as in [backpack_3d.launch](https://github.com/googlecartographer/cartographer_ros/blob/master/cartographer_ros/launch/backpack_3d.launch#L29)

If this doesn't answer your question, please clarify what you mean with "suitable drive".
