### ISSUE TITLE
Conflicting odometry?

### ISSUE THREAD

**Issue by sabetAI** [cartographer-project/cartographer_ros#984]
I think I'm getting conflicting odometry between cartographer and another node, when I view the /scan topic I get this:

![image](https://user-images.githubusercontent.com/28828395/44280147-7d9b1e00-a219-11e8-881d-f2d9d48d410c.png)

![image](https://user-images.githubusercontent.com/28828395/44280161-84299580-a219-11e8-887b-6532efbef110.png)

Viewing the tf-tree in rviz, I see the position and orientation values for all frames changing erratically even though the robot is stationary. I'm running the cartographer node on a jackal robot, but am using the settings from backpack_2d config file (it used to work at some point). My settings are:

```
include "map_builder.lua"
include "trajectory_builder.lua"

options = {
  map_builder = MAP_BUILDER,
  trajectory_builder = TRAJECTORY_BUILDER,
  map_frame = "map",
  tracking_frame = "base_link",
  published_frame = "base_link",
  odom_frame = "odom",
  provide_odom_frame = true,
  publish_frame_projected_to_2d = false,
  use_odometry = false,
  use_nav_sat = false,
  use_landmarks = false,
  num_laser_scans = 1,
  num_multi_echo_laser_scans = 0,
  num_subdivisions_per_laser_scan = 10,
  num_point_clouds = 0,
  lookup_transform_timeout_sec = 0.2,
  submap_publish_period_sec = 0.3,
  pose_publish_period_sec = 5e-3,
  trajectory_publish_period_sec = 30e-3,
  rangefinder_sampling_ratio = 1.,
  odometry_sampling_ratio = 1.,
  fixed_frame_pose_sampling_ratio = 1.,
  imu_sampling_ratio = 1.,
  landmarks_sampling_ratio = 1.,
}

MAP_BUILDER.use_trajectory_builder_2d = true
TRAJECTORY_BUILDER_2D.num_accumulated_range_data = 10

return options

```

And my launch file is:

<launch>
  <node name="cartographer_node" pkg="cartographer_ros"
      type="cartographer_node" args="
          -configuration_directory
              $(find cartographer_ros)/configuration_files
          -configuration_basename jackal_2d.lua"
      output="screen">
    <remap from="scan" to="/scan" />
    <remap from="odom" to="odometry/filtered" />
    <remap from="imu" to="imu/data"/>
 </node>

    <node name="cartographer_occupancy_grid_node" pkg="cartographer_ros"
      type="cartographer_occupancy_grid_node" args="-resolution 0.05" />
</launch>

How can I resolve this issue?

**Comment by kdaun** [comment]
Which frame are you showing in RViz?

Potential reasons for such erroneous behaviors are wrong transformations in the URDF or frame fighting by multiple nodes publishing the same TF transform (e.g. map to odom).

Can you please run
`rosrun tf view_frames`
and post the resulting graph?
