### ISSUE TITLE
few INTER Constraints when doing Pure Localization 3D SLAM

### ISSUE THREAD

**Issue by edward0im** [cartographer-project/cartographer_ros#993]
Hello, cartographer's developers :-)
first, Thank you for offering very useful SLAM algorithm I can use it for study, research purposes

I'm using Cartographer 3D SLAM with a vehicle (a Velodyne HDL-64E, IMU equipped) for study purpose.
and I hope my vehicle can localize itself in global offline map (`.pbstream`) I made.

but I think there are few INTER constraints between 2 trajectories which cause bad performance in Pure Localization. 

- ### Cartographer's demo_backpack_3d's INTER Constraints (Orange Line)
![17](https://user-images.githubusercontent.com/18214498/44629517-8b744000-a98b-11e8-8c4e-b6422f9c950a.png)
![18](https://user-images.githubusercontent.com/18214498/44629518-8b744000-a98b-11e8-890b-1ff9e712ee41.png)

- ### my vehicle data's INTER Constraints (Orange Line)
![20](https://user-images.githubusercontent.com/18214498/44629522-9929c580-a98b-11e8-8752-cd3e09d12714.png)
![21](https://user-images.githubusercontent.com/18214498/44629519-8d3e0380-a98b-11e8-9c30-932f0d57ea64.png)

my questions are 

---
1. Can I tune INTER constraints by modifying cartographer's parameter? (e.g. `constraint builder`, ...)
---
2. why my submaps are NOT clear and don't have free spaces (white color) as much as demo_backpack_3d`'s submaps? is it because of frequency of velodyne_points topic?
    2.1. (mine is 10 Hz, demo is 1500 Hz)
    2.2. (urdf file is find and the poses of velodyne sensor & IMU are almost precise)
![02](https://user-images.githubusercontent.com/18214498/45090209-a8f29800-b149-11e8-8c27-dc837d2e0989.PNG)
---
3. I think it CAN do Pure Localization near starting point of global offline submap with SAME bag file after making offline map. but not a further point. Is it a normal situation or I did something wrong?
![22](https://user-images.githubusercontent.com/18214498/44629822-62ee4500-a98f-11e8-98ef-9c2886d8c57b.png)

Thank you in advance! :-)

**Comment by tigerk0430** [comment]
- urdf file
https://gist.github.com/tigerk0430/b65b17e53f8a5a8c84306ace95caaff0
- rosbag_validate
https://gist.github.com/tigerk0430/02433034acca8f23f4e8916639426496
-

**Comment by rqren2008** [comment]
Have you tried to do something like this?
https://google-cartographer-ros.readthedocs.io/en/latest/tuning.html#pure-localization-in-a-given-map

**Comment by gaschler** [comment]
> 1. Can I tune INTER constraints by modifying cartographer's parameter? (e.g. constraint builder, ...)

You will have more loop closure constraints when you 
increase `POSE_GRAPH.constraint_builder.sampling_ratio`
decrease `POSE_GRAPH.constraint_builder.min_score`


> 2. why my submaps are NOT clear and don't have free spaces (white color) as much as demo_backpack_3d`'s submaps? is it because of frequency of velodyne_points topic?
> 2.1. (mine is 10 Hz, demo is 1500 Hz)
> 2.2. (urdf file is find and the poses of velodyne sensor & IMU are almost precise)

You need to adapt TRAJECTORY_BUILDER_3D.num_accumulated_range_data and submaps.num_range_data to your frequency.
One submap should appear every 5-30 seconds.
You could post your changes to the configuration so we can take a look.

> 3. I think it CAN do Pure Localization near starting point of global offline submap with SAME bag file after making offline map. but not a further point. Is it a normal situation or I did something wrong?

Global localization in 3D takes time. You can increase thread numbers, increase global_sampling_ratio, decrease global_localization_min_score, but make sure you don't overload your cpus (otherwise background work falls behind).

**Comment by tigerk0430** [comment]
Thank you for the answer :-) 

I focused on NO.2 question's answer which is about map's definition
I tuned parameters like what you adviced, but thing aren't different as much as I expected :-/

here's results  
### Submaps
![01](https://user-images.githubusercontent.com/18214498/45207318-a9fb0500-b2c2-11e8-86e6-76beb26510d7.png)
![02](https://user-images.githubusercontent.com/18214498/45207319-aa939b80-b2c2-11e8-90ae-3ed4079753b0.png)
![03](https://user-images.githubusercontent.com/18214498/45207320-aa939b80-b2c2-11e8-9743-f54913c3bea2.png)
![04](https://user-images.githubusercontent.com/18214498/45207322-aa939b80-b2c2-11e8-8e0d-c72ba08b1d1d.png)
![05](https://user-images.githubusercontent.com/18214498/45207323-aa939b80-b2c2-11e8-8aa8-5d2d98754641.png)  

### Maps
![06](https://user-images.githubusercontent.com/18214498/45207324-ab2c3200-b2c2-11e8-8bc3-a58db84ea855.png)
![07](https://user-images.githubusercontent.com/18214498/45207325-ab2c3200-b2c2-11e8-8c03-2a70f0036835.png)
![08](https://user-images.githubusercontent.com/18214498/45207326-ab2c3200-b2c2-11e8-9306-d0e34260f255.png)
![09](https://user-images.githubusercontent.com/18214498/45207329-abc4c880-b2c2-11e8-8723-2459a4155518.png)
![10](https://user-images.githubusercontent.com/18214498/45207330-abc4c880-b2c2-11e8-83d3-b0314e382879.png)

**Comment by rqren2008** [comment]
Hi,Your map looks very vell, I have two questions now
1.Does loop closure work in this case?
2.Have you tried pure location based this map? 
Thanks very much!

**Comment by rqren2008** [comment]
And, could you show your configure files?

**Comment by tigerk0430** [comment]
@rqren2008 
1. if Loop Closure means global SLAM, then YES. It's trying to match 2 different trajectories by using Pure Localization Mode. but as you know, Pure Localization Mode deletes previous submaps every 3 cycles then It can't do Loop Closure perfectly.
2. YES. the Issue I posted is about INNER Constraint Problem when doing Pure Localization.

my configuration files are here  

`settings_test.lua`
- https://gist.github.com/tigerk0430/c650fb71122d6a4a1a18c4c7a521f641

`map_builder_test.lua`
- https://gist.github.com/tigerk0430/fcbfa5b4365efa3269f9d41e3ae68e2c

`pose_graph_test.lua`
- https://gist.github.com/tigerk0430/21c24b235bd097d2ca60b74c28b53b60

`pose_graph_test_localization.lua`
- https://gist.github.com/tigerk0430/a7bb2a5b1bc4555067052769ee9b7a03

`trajectory_builder_test.lua`
- https://gist.github.com/tigerk0430/064d81bb5708e1dcbab06b13dcc23022

`trajectory_builder_3d_test.lua`
- https://gist.github.com/tigerk0430/c999e1d296637caaa9a0fc43acc5b76f

**Comment by RonaldEnsing** [comment]
> why my submaps are NOT clear and don't have free spaces (white color) as much as demo_backpack_3d`'s submaps?

I would be interested in this as well, since the same happens on my data and only in 3D mode.

**Comment by MichaelGrupp** [comment]
The 3D grid data structure is sparse for efficiency.

**Comment by Difeng1987** [comment]
What the final solution for this issue, i am facing the totally same issue, i am using VLP16 radar.

Thanks.

BR
