### ISSUE TITLE
Lidar data format

### ISSUE THREAD

**Issue by 3pi10** [cartographer-project/cartographer_ros#998]
Hi, 

I am using velodyne hdl64 and per ros pointcloud2 message I have only 18 degree of a whole circle worth of data. Wondering if Cartographer support this or I have to merge one whole spin per message. Or if there is a setting that I can tell cartographer to use 20 messages before matching it to a submap? The result I am getting is a dense spherical point cloud that amlost everything is not matched and after playing with parameters the spherical transferemed to a cylinder of dense points still no matching. For some reason the orientation of scans changing unreastically big and I am guessing that cause mapping fails. No bias in imu data.

Sorry I can not provide data! The cartographer bag check did not give any error

**Comment by kdaun** [comment]
The parameter `num_accumulated_range_data` sets the "_number of range data to accumulate into one unwarped, combined range data to use for scan matching_" (see [documentation](https://google-cartographer.readthedocs.io/en/latest/configuration.html)).
If you are using the 3D pipeline, try adding `TRAJECTORY_BUILDER_3D.num_accumulated_range_data = 20` to your configuration file to combine 20 scans per scan match.

**Comment by bochen87** [comment]
Cartographer supports both 2D and 3D. However, if you only have 18 degrees of the full circle worth of Scans from you velodyne, something is wrong. You’re effectively only using 5% of the data that your Lidar scan returns. Any sort of slam will be difficult with that.
